// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

// interfaces

// enums

// package - factory- constants
export * from "./EmptyPackage.js"
export * from "./EmptyFactory.js"
export * from "./EmptyConstants.js"

// implementations
export * from "./EmptyPackageImpl.js"
export * from "./EmptyFactoryImpl.js"
