// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

export enum MatchKind {
    FINAL = 4,
    QUARTER_FINAL = 2,
    ROUND_OF16 = 1,
    ROUND_OF32 = 0,
    SEMI_FINAL = 3
}

export function matchKindToString(matchKind: MatchKind): string {
    switch (matchKind) {
        case MatchKind.FINAL:
            return "Final"
        case MatchKind.QUARTER_FINAL:
            return "QuarterFinal"
        case MatchKind.ROUND_OF16:
            return "RoundOf16"
        case MatchKind.ROUND_OF32:
            return "RoundOf32"
        case MatchKind.SEMI_FINAL:
            return "SemiFinal"
    }
}

export function matchKindFromString(literalValue: string): MatchKind {
    switch (literalValue) {
        case "Final":
            return MatchKind.FINAL
        case "QuarterFinal":
            return MatchKind.QUARTER_FINAL
        case "RoundOf16":
            return MatchKind.ROUND_OF16
        case "RoundOf32":
            return MatchKind.ROUND_OF32
        case "SemiFinal":
            return MatchKind.SEMI_FINAL
        default:
            throw new Error("Invalid value for enum MatchKind: " + literalValue)
    }
}
