// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

import { describe, expect, test } from "vitest"
import { anything, capture, instance, mock, reset, verify, when } from "ts-mockito"
import * as ecore from "@masagroup/ecore"
import { NamedElementImpl, TournamentConstants, getTournamentPackage } from "./internal.js"

describe("NamedElementImpl", () => {
    test("eStaticClass", () => {
        let o = new NamedElementImpl()
        expect(o.eStaticClass()).toBe(getTournamentPackage().getNamedElement())
    })

    test("getName", () => {
        let o = new NamedElementImpl()
        // get default value
        expect(o.getName()).toBe("")
    })

    test("setName", () => {
        let o = new NamedElementImpl()
        let value = "Test String"

        // add listener
        let mockAdapter = mock<ecore.EAdapter>()
        let adapter = instance(mockAdapter)
        o.eAdapters().add(adapter)

        // set value
        o.setName(value)

        // checks
        verify(mockAdapter.notifyChanged(anything())).once()
        const [notification] = capture(mockAdapter.notifyChanged).last()
        expect(notification.getNotifier()).toBe(o)
        expect(notification.getOldValue()).toBe("")
        expect(notification.getNewValue()).toBe(value)
        expect(notification.getPosition()).toBe(-1)
    })

    test("eGetFromID", () => {
        let o = new NamedElementImpl()
        expect(() => o.eGetFromID(-1, true)).toThrow(Error)
        expect(o.eGetFromID(TournamentConstants.NAMED_ELEMENT__NAME, true)).toStrictEqual(o.getName())
    })

    test("eSetFromID", () => {
        let o = new NamedElementImpl()
        expect(() => o.eSetFromID(-1, null)).toThrow(Error)
        {
            let value = "Test String"
            o.eSetFromID(TournamentConstants.NAMED_ELEMENT__NAME, value)
            expect(o.eGetFromID(TournamentConstants.NAMED_ELEMENT__NAME, false)).toBe(value)
        }
    })

    test("eIsSetFromID", () => {
        let o = new NamedElementImpl()
        expect(() => o.eIsSetFromID(-1)).toThrow(Error)
        expect(o.eIsSetFromID(TournamentConstants.NAMED_ELEMENT__NAME)).toBeFalsy()
    })

    test("eUnsetFromID", () => {
        let o = new NamedElementImpl()
        expect(() => o.eUnsetFromID(-1)).toThrow(Error)
        {
            o.eUnsetFromID(TournamentConstants.NAMED_ELEMENT__NAME)
            let v = o.eGetFromID(TournamentConstants.NAMED_ELEMENT__NAME, false)
            expect(v).toBe("")
        }
    })
})
