// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

import {
    BasicEDataTypeList,
    BasicEList,
    BasicEObjectList,
    BasicEObjectMap,
    EAnnotation,
    EClass,
    EList,
    EMap,
    EMapEntry,
    EModelElement,
    EModelElementExt,
    ENotification,
    ENotificationChain,
    ENotifyingList,
    EOPPOSITE_FEATURE_BASE,
    EObject,
    EObjectInternal,
    EStringToStringMapEntry,
    EcoreConstants,
    EventType,
    Notification,
    getEcorePackage,
    isEObjectInternal,
    isEObjectList,
} from "./internal";

export class EAnnotationImpl extends EModelElementExt implements EAnnotation {
    protected _source: string;
    protected _references: EList<EObject>;
    protected _contents: EList<EObject>;
    protected _details: EMap<string, string>;

    constructor() {
        super();
        this._contents = null;
        this._details = null;
        this._references = null;
        this._source = "";
    }

    eStaticClass(): EClass {
        return getEcorePackage().getEAnnotationClass();
    }

    // get the value of contents
    get contents(): EList<EObject> {
        if (this._contents == null) {
            this._contents = this.initContents();
        }
        return this._contents;
    }

    // get the value of details
    get details(): EMap<string, string> {
        if (this._details == null) {
            this._details = this.initDetails();
        }
        return this._details;
    }

    // get the value of eModelElement
    get eModelElement(): EModelElement {
        if (this.eContainerFeatureID() == EcoreConstants.EANNOTATION__EMODEL_ELEMENT) {
            return this.eContainer() as EModelElement;
        }
        return null;
    }

    // set the value of eModelElement
    set eModelElement(newEModelElement: EModelElement) {
        if (
            newEModelElement != this.eInternalContainer() ||
            (newEModelElement != null &&
                this.eContainerFeatureID() != EcoreConstants.EANNOTATION__EMODEL_ELEMENT)
        ) {
            let notifications: ENotificationChain = null;
            if (this.eInternalContainer() != null) {
                notifications = this.eBasicRemoveFromContainer(notifications);
            }
            if (isEObjectInternal(newEModelElement)) {
                notifications = newEModelElement.eInverseAdd(
                    this,
                    EcoreConstants.EMODEL_ELEMENT__EANNOTATIONS,
                    notifications,
                );
            }
            notifications = this.basicSetEModelElement(newEModelElement, notifications);
            if (notifications != null) {
                notifications.dispatch();
            }
        } else if (this.eNotificationRequired) {
            this.eNotify(
                new Notification(
                    this,
                    EventType.SET,
                    EcoreConstants.EANNOTATION__EMODEL_ELEMENT,
                    newEModelElement,
                    newEModelElement,
                ),
            );
        }
    }

    basicSetEModelElement(
        newEModelElement: EModelElement,
        msgs: ENotificationChain,
    ): ENotificationChain {
        return this.eBasicSetContainer(
            newEModelElement,
            EcoreConstants.EANNOTATION__EMODEL_ELEMENT,
            msgs,
        );
    }

    // get the value of references
    get references(): EList<EObject> {
        if (this._references == null) {
            this._references = this.initReferences();
        }
        return this._references;
    }

    // get the value of source
    get source(): string {
        return this._source;
    }

    // set the value of source
    set source(newSource: string) {
        let oldSource = this._source;
        this._source = newSource;
        if (this.eNotificationRequired) {
            this.eNotify(
                new Notification(
                    this,
                    EventType.SET,
                    EcoreConstants.EANNOTATION__SOURCE,
                    oldSource,
                    newSource,
                ),
            );
        }
    }

    protected initContents(): EList<EObject> {
        return new BasicEObjectList<EObject>(
            this,
            EcoreConstants.EANNOTATION__CONTENTS,
            -1,
            true,
            true,
            false,
            false,
            false,
        );
    }
    protected initDetails(): EMap<string, string> {
        return new BasicEObjectMap<string, string>(getEcorePackage().getEStringToStringMapEntry());
    }
    protected initReferences(): EList<EObject> {
        return new BasicEObjectList<EObject>(
            this,
            EcoreConstants.EANNOTATION__REFERENCES,
            -1,
            false,
            false,
            false,
            true,
            false,
        );
    }

    eGetFromID(featureID: number, resolve: boolean): any {
        switch (featureID) {
            case EcoreConstants.EANNOTATION__CONTENTS: {
                return this.contents;
            }
            case EcoreConstants.EANNOTATION__DETAILS: {
                return this.details;
            }
            case EcoreConstants.EANNOTATION__EMODEL_ELEMENT: {
                return this.eModelElement;
            }
            case EcoreConstants.EANNOTATION__REFERENCES: {
                let list = this.references;
                if (!resolve) {
                    if (isEObjectList(list)) return list.getUnResolvedList();
                }
                return list;
            }
            case EcoreConstants.EANNOTATION__SOURCE: {
                return this.source;
            }
            default: {
                return super.eGetFromID(featureID, resolve);
            }
        }
    }

    eSetFromID(featureID: number, newValue: any) {
        switch (featureID) {
            case EcoreConstants.EANNOTATION__CONTENTS: {
                this.contents.clear();
                this.contents.addAll(newValue as EList<EObject>);
                break;
            }
            case EcoreConstants.EANNOTATION__DETAILS: {
                this.details.clear();
                this.details.addAll(newValue as EList<EMapEntry<string, string>>);
                break;
            }
            case EcoreConstants.EANNOTATION__EMODEL_ELEMENT: {
                this.eModelElement = newValue as EModelElement;
                break;
            }
            case EcoreConstants.EANNOTATION__REFERENCES: {
                this.references.clear();
                this.references.addAll(newValue as EList<EObject>);
                break;
            }
            case EcoreConstants.EANNOTATION__SOURCE: {
                this.source = newValue as string;
                break;
            }
            default: {
                super.eSetFromID(featureID, newValue);
            }
        }
    }

    eUnsetFromID(featureID: number) {
        switch (featureID) {
            case EcoreConstants.EANNOTATION__CONTENTS: {
                this.contents.clear();
                break;
            }
            case EcoreConstants.EANNOTATION__DETAILS: {
                this.details.clear();
                break;
            }
            case EcoreConstants.EANNOTATION__EMODEL_ELEMENT: {
                this.eModelElement = null;
                break;
            }
            case EcoreConstants.EANNOTATION__REFERENCES: {
                this.references.clear();
                break;
            }
            case EcoreConstants.EANNOTATION__SOURCE: {
                this.source = "";
                break;
            }
            default: {
                super.eUnsetFromID(featureID);
            }
        }
    }

    eIsSetFromID(featureID: number): boolean {
        switch (featureID) {
            case EcoreConstants.EANNOTATION__CONTENTS: {
                return this.contents != null && this.contents.size() != 0;
            }
            case EcoreConstants.EANNOTATION__DETAILS: {
                return this.details != null && this.details.size() != 0;
            }
            case EcoreConstants.EANNOTATION__EMODEL_ELEMENT: {
                return this.eModelElement != null;
            }
            case EcoreConstants.EANNOTATION__REFERENCES: {
                return this.references != null && this.references.size() != 0;
            }
            case EcoreConstants.EANNOTATION__SOURCE: {
                return this._source != "";
            }
            default: {
                return super.eIsSetFromID(featureID);
            }
        }
    }

    eBasicInverseAdd(
        otherEnd: EObject,
        featureID: number,
        notifications: ENotificationChain,
    ): ENotificationChain {
        switch (featureID) {
            case EcoreConstants.EANNOTATION__EMODEL_ELEMENT: {
                let msgs = notifications;
                if (this.eContainer() != null) {
                    msgs = this.eBasicRemoveFromContainer(msgs);
                }
                return this.basicSetEModelElement(otherEnd as EModelElement, msgs);
            }
            default: {
                return super.eBasicInverseAdd(otherEnd, featureID, notifications);
            }
        }
    }

    eBasicInverseRemove(
        otherEnd: EObject,
        featureID: number,
        notifications: ENotificationChain,
    ): ENotificationChain {
        switch (featureID) {
            case EcoreConstants.EANNOTATION__CONTENTS: {
                let list = this.contents as ENotifyingList<EObject>;
                let end = otherEnd as EObject;
                return list.removeWithNotification(end, notifications);
            }
            case EcoreConstants.EANNOTATION__DETAILS: {
                return notifications;
            }
            case EcoreConstants.EANNOTATION__EMODEL_ELEMENT: {
                return this.basicSetEModelElement(null, notifications);
            }
            default: {
                return super.eBasicInverseRemove(otherEnd, featureID, notifications);
            }
        }
    }
}
