// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

import { anything, capture, instance, mock, verify } from "ts-mockito"
import { describe, expect, test } from "vitest"
import { EAdapter, EAttributeImpl, EDataType, EObjectInternal, EcoreConstants, getEcorePackage } from "./internal.js"

interface EDataTypeInternal extends EDataType, EObjectInternal {}

describe("EAttributeImpl", () => {
    test("eStaticClass", () => {
        const o = new EAttributeImpl()
        expect(o.eStaticClass()).toBe(getEcorePackage().getEAttribute())
    })

    test("getEAttributeType", () => {
        const o = new EAttributeImpl()
        expect(() => o.getEAttributeType()).toThrow(Error)
    })

    test("getID", () => {
        const o = new EAttributeImpl()
        // get default value
        expect(o.isID()).toBe(false)
    })

    test("setID", () => {
        const o = new EAttributeImpl()
        const value = true

        // add listener
        const mockAdapter = mock<EAdapter>()
        const adapter = instance(mockAdapter)
        o.eAdapters().add(adapter)

        // set value
        o.setID(value)

        // checks
        verify(mockAdapter.notifyChanged(anything())).once()
        const [notification] = capture(mockAdapter.notifyChanged).last()
        expect(notification.getNotifier()).toBe(o)
        expect(notification.getOldValue()).toBe(false)
        expect(notification.getNewValue()).toBe(value)
        expect(notification.getPosition()).toBe(-1)
    })

    test("eGetFromID", () => {
        const o = new EAttributeImpl()
        expect(() => o.eGetFromID(-1, true)).toThrow(Error)
        expect(() => o.eGetFromID(EcoreConstants.EATTRIBUTE__EATTRIBUTE_TYPE, true)).toThrow(Error)
        expect(() => o.eGetFromID(EcoreConstants.EATTRIBUTE__EATTRIBUTE_TYPE, false)).toThrow(Error)
        expect(o.eGetFromID(EcoreConstants.EATTRIBUTE__ID, true)).toStrictEqual(o.isID())
    })

    test("eSetFromID", () => {
        const o = new EAttributeImpl()
        expect(() => o.eSetFromID(-1, null)).toThrow(Error)
        {
            const value = true
            o.eSetFromID(EcoreConstants.EATTRIBUTE__ID, value)
            expect(o.eGetFromID(EcoreConstants.EATTRIBUTE__ID, false)).toBe(value)
        }
    })

    test("eIsSetFromID", () => {
        const o = new EAttributeImpl()
        expect(() => o.eIsSetFromID(-1)).toThrow(Error)
        expect(() => o.eIsSetFromID(EcoreConstants.EATTRIBUTE__EATTRIBUTE_TYPE)).toThrow(Error)
        expect(o.eIsSetFromID(EcoreConstants.EATTRIBUTE__ID)).toBeFalsy()
    })

    test("eUnsetFromID", () => {
        const o = new EAttributeImpl()
        expect(() => o.eUnsetFromID(-1)).toThrow(Error)
        {
            o.eUnsetFromID(EcoreConstants.EATTRIBUTE__ID)
            const v = o.eGetFromID(EcoreConstants.EATTRIBUTE__ID, false)
            expect(v).toBe(false)
        }
    })
})
