// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

import { ENamedElement, EPackage } from "./internal.js"

export interface EClassifier extends ENamedElement {
    // instanceClassName
    getInstanceClassName(): string
    setInstanceClassName(newInstanceClassName: string): void

    // instanceClass
    getInstanceClass(): any
    setInstanceClass(newInstanceClass: any): void

    // instanceTypeName
    getInstanceTypeName(): string
    setInstanceTypeName(newInstanceTypeName: string): void

    // defaultValue
    getDefaultValue(): any

    // ePackage
    getEPackage(): EPackage

    // classifierID
    getClassifierID(): number
    setClassifierID(newClassifierID: number): void

    // operations
    isInstance(object: any): boolean
}
