// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

import { EAttribute, EClassifier, EList, EOperation, EReference, EStructuralFeature } from "./internal.js"

export interface EClass extends EClassifier {
    // abstract
    isAbstract(): boolean
    setAbstract(newIsAbstract: boolean): void

    // interface
    isInterface(): boolean
    setInterface(newIsInterface: boolean): void

    // eStructuralFeatures
    getEStructuralFeatures(): EList<EStructuralFeature>

    // eAttributes
    getEAttributes(): EList<EAttribute>

    // eReferences
    getEReferences(): EList<EReference>

    // eSuperTypes
    getESuperTypes(): EList<EClass>

    // eOperations
    getEOperations(): EList<EOperation>

    // eContainmentFeatures
    getEContainmentFeatures(): EList<EStructuralFeature>

    // eCrossReferenceFeatures
    getECrossReferenceFeatures(): EList<EStructuralFeature>

    // eAllAttributes
    getEAllAttributes(): EList<EAttribute>

    // eAllReferences
    getEAllReferences(): EList<EReference>

    // eAllContainments
    getEAllContainments(): EList<EReference>

    // eAllCrossReferences
    getEAllCrossReferences(): EList<EReference>

    // eAllOperations
    getEAllOperations(): EList<EOperation>

    // eAllStructuralFeatures
    getEAllStructuralFeatures(): EList<EStructuralFeature>

    // eAllSuperTypes
    getEAllSuperTypes(): EList<EClass>

    // eIDAttribute
    getEIDAttribute(): EAttribute

    // operations
    isSuperTypeOf(someClass: EClass): boolean
    getFeatureCount(): number
    getEStructuralFeature(featureID: number): EStructuralFeature
    getEStructuralFeatureFromName(featureName: string): EStructuralFeature
    getFeatureID(feature: EStructuralFeature): number
    getOperationCount(): number
    getEOperation(operationID: number): EOperation
    getOperationID(operation: EOperation): number
    getOverride(operation: EOperation): EOperation
    getFeatureType(feature: EStructuralFeature): EClassifier
}
