// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group                                                 
//                                                                              
// This Source Code Form is subject to the terms of the Mozilla Public          
// License, v. 2.0. If a copy of the MPL was not distributed with this          
// file, You can obtain one at https://mozilla.org/MPL/2.0/.                    
//                                                                              
// *****************************************************************************


export class EcoreConstants {

    public static readonly eNAME: string = "ecore"

    public static readonly eNS_URI: string = "http://www.eclipse.org/emf/2002/Ecore"

    public static readonly eNS_PREFIX: string = "ecore"

    // EMODEL_ELEMENT is the meta object id for the class EModelElement.
    public static readonly EMODEL_ELEMENT: number = 8
    
    // EMODEL_ELEMENT__EANNOTATIONS is the feature id for the EModelElement 'EAnnotations' containment reference list.
    public static readonly EMODEL_ELEMENT__EANNOTATIONS: number = 0
    
    
    // EMODEL_ELEMENT_FEATURE_COUNT is the number of structural features of the class EModelElement.
    public static readonly EMODEL_ELEMENT_FEATURE_COUNT: number = 1
    
    // EMODEL_ELEMENT__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly EMODEL_ELEMENT__GET_EANNOTATION_ESTRING: number = 0
    
    // EMODEL_ELEMENT_OPERATION_COUNT is the number of EMODEL_ELEMENT_OPERATION_COUNT.
    public static readonly EMODEL_ELEMENT_OPERATION_COUNT: number = 1
    
    // ENAMED_ELEMENT is the meta object id for the class ENamedElement.
    public static readonly ENAMED_ELEMENT: number = 9
    
    // ENAMED_ELEMENT__EANNOTATIONS is the feature id for the ENamedElement 'EAnnotations' containment reference list.
    public static readonly ENAMED_ELEMENT__EANNOTATIONS: number = 0
    
    // ENAMED_ELEMENT__NAME is the feature id for the ENamedElement 'Name' attribute.
    public static readonly ENAMED_ELEMENT__NAME: number = 1
    
    
    // ENAMED_ELEMENT_FEATURE_COUNT is the number of structural features of the class ENamedElement.
    public static readonly ENAMED_ELEMENT_FEATURE_COUNT: number = 2
    
    // ENAMED_ELEMENT__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly ENAMED_ELEMENT__GET_EANNOTATION_ESTRING: number = 0
    
    // ENAMED_ELEMENT_OPERATION_COUNT is the number of ENAMED_ELEMENT_OPERATION_COUNT.
    public static readonly ENAMED_ELEMENT_OPERATION_COUNT: number = 1
    
    // ETYPED_ELEMENT is the meta object id for the class ETypedElement.
    public static readonly ETYPED_ELEMENT: number = 16
    
    // ETYPED_ELEMENT__EANNOTATIONS is the feature id for the ETypedElement 'EAnnotations' containment reference list.
    public static readonly ETYPED_ELEMENT__EANNOTATIONS: number = 0
    
    // ETYPED_ELEMENT__NAME is the feature id for the ETypedElement 'Name' attribute.
    public static readonly ETYPED_ELEMENT__NAME: number = 1
    
    // ETYPED_ELEMENT__ORDERED is the feature id for the ETypedElement 'IsOrdered' attribute.
    public static readonly ETYPED_ELEMENT__ORDERED: number = 2
    
    // ETYPED_ELEMENT__UNIQUE is the feature id for the ETypedElement 'IsUnique' attribute.
    public static readonly ETYPED_ELEMENT__UNIQUE: number = 3
    
    // ETYPED_ELEMENT__LOWER_BOUND is the feature id for the ETypedElement 'LowerBound' attribute.
    public static readonly ETYPED_ELEMENT__LOWER_BOUND: number = 4
    
    // ETYPED_ELEMENT__UPPER_BOUND is the feature id for the ETypedElement 'UpperBound' attribute.
    public static readonly ETYPED_ELEMENT__UPPER_BOUND: number = 5
    
    // ETYPED_ELEMENT__MANY is the feature id for the ETypedElement 'IsMany' attribute.
    public static readonly ETYPED_ELEMENT__MANY: number = 6
    
    // ETYPED_ELEMENT__REQUIRED is the feature id for the ETypedElement 'IsRequired' attribute.
    public static readonly ETYPED_ELEMENT__REQUIRED: number = 7
    
    // ETYPED_ELEMENT__ETYPE is the feature id for the ETypedElement 'EType' reference.
    public static readonly ETYPED_ELEMENT__ETYPE: number = 8
    
    
    // ETYPED_ELEMENT_FEATURE_COUNT is the number of structural features of the class ETypedElement.
    public static readonly ETYPED_ELEMENT_FEATURE_COUNT: number = 9
    
    // ETYPED_ELEMENT__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly ETYPED_ELEMENT__GET_EANNOTATION_ESTRING: number = 0
    
    // ETYPED_ELEMENT_OPERATION_COUNT is the number of ETYPED_ELEMENT_OPERATION_COUNT.
    public static readonly ETYPED_ELEMENT_OPERATION_COUNT: number = 1
    
    // ESTRUCTURAL_FEATURE is the meta object id for the class EStructuralFeature.
    public static readonly ESTRUCTURAL_FEATURE: number = 15
    
    // ESTRUCTURAL_FEATURE__EANNOTATIONS is the feature id for the EStructuralFeature 'EAnnotations' containment reference list.
    public static readonly ESTRUCTURAL_FEATURE__EANNOTATIONS: number = 0
    
    // ESTRUCTURAL_FEATURE__NAME is the feature id for the EStructuralFeature 'Name' attribute.
    public static readonly ESTRUCTURAL_FEATURE__NAME: number = 1
    
    // ESTRUCTURAL_FEATURE__ORDERED is the feature id for the EStructuralFeature 'IsOrdered' attribute.
    public static readonly ESTRUCTURAL_FEATURE__ORDERED: number = 2
    
    // ESTRUCTURAL_FEATURE__UNIQUE is the feature id for the EStructuralFeature 'IsUnique' attribute.
    public static readonly ESTRUCTURAL_FEATURE__UNIQUE: number = 3
    
    // ESTRUCTURAL_FEATURE__LOWER_BOUND is the feature id for the EStructuralFeature 'LowerBound' attribute.
    public static readonly ESTRUCTURAL_FEATURE__LOWER_BOUND: number = 4
    
    // ESTRUCTURAL_FEATURE__UPPER_BOUND is the feature id for the EStructuralFeature 'UpperBound' attribute.
    public static readonly ESTRUCTURAL_FEATURE__UPPER_BOUND: number = 5
    
    // ESTRUCTURAL_FEATURE__MANY is the feature id for the EStructuralFeature 'IsMany' attribute.
    public static readonly ESTRUCTURAL_FEATURE__MANY: number = 6
    
    // ESTRUCTURAL_FEATURE__REQUIRED is the feature id for the EStructuralFeature 'IsRequired' attribute.
    public static readonly ESTRUCTURAL_FEATURE__REQUIRED: number = 7
    
    // ESTRUCTURAL_FEATURE__ETYPE is the feature id for the EStructuralFeature 'EType' reference.
    public static readonly ESTRUCTURAL_FEATURE__ETYPE: number = 8
    
    // ESTRUCTURAL_FEATURE__CHANGEABLE is the feature id for the EStructuralFeature 'IsChangeable' attribute.
    public static readonly ESTRUCTURAL_FEATURE__CHANGEABLE: number = 9
    
    // ESTRUCTURAL_FEATURE__VOLATILE is the feature id for the EStructuralFeature 'IsVolatile' attribute.
    public static readonly ESTRUCTURAL_FEATURE__VOLATILE: number = 10
    
    // ESTRUCTURAL_FEATURE__TRANSIENT is the feature id for the EStructuralFeature 'IsTransient' attribute.
    public static readonly ESTRUCTURAL_FEATURE__TRANSIENT: number = 11
    
    // ESTRUCTURAL_FEATURE__DEFAULT_VALUE_LITERAL is the feature id for the EStructuralFeature 'DefaultValueLiteral' attribute.
    public static readonly ESTRUCTURAL_FEATURE__DEFAULT_VALUE_LITERAL: number = 12
    
    // ESTRUCTURAL_FEATURE__DEFAULT_VALUE is the feature id for the EStructuralFeature 'DefaultValue' attribute.
    public static readonly ESTRUCTURAL_FEATURE__DEFAULT_VALUE: number = 13
    
    // ESTRUCTURAL_FEATURE__UNSETTABLE is the feature id for the EStructuralFeature 'IsUnsettable' attribute.
    public static readonly ESTRUCTURAL_FEATURE__UNSETTABLE: number = 14
    
    // ESTRUCTURAL_FEATURE__DERIVED is the feature id for the EStructuralFeature 'IsDerived' attribute.
    public static readonly ESTRUCTURAL_FEATURE__DERIVED: number = 15
    
    // ESTRUCTURAL_FEATURE__ECONTAINING_CLASS is the feature id for the EStructuralFeature 'EContainingClass' container reference.
    public static readonly ESTRUCTURAL_FEATURE__ECONTAINING_CLASS: number = 16
    
    // ESTRUCTURAL_FEATURE__FEATURE_ID is the feature id for the EStructuralFeature 'FeatureID' attribute.
    public static readonly ESTRUCTURAL_FEATURE__FEATURE_ID: number = 17
    
    
    // ESTRUCTURAL_FEATURE_FEATURE_COUNT is the number of structural features of the class EStructuralFeature.
    public static readonly ESTRUCTURAL_FEATURE_FEATURE_COUNT: number = 18
    
    // ESTRUCTURAL_FEATURE__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly ESTRUCTURAL_FEATURE__GET_EANNOTATION_ESTRING: number = 0
    // ESTRUCTURAL_FEATURE__GET_CONTAINER_CLASS is the operation id for the 'getContainerClass' operation.
    public static readonly ESTRUCTURAL_FEATURE__GET_CONTAINER_CLASS: number = 1
    
    // ESTRUCTURAL_FEATURE_OPERATION_COUNT is the number of ESTRUCTURAL_FEATURE_OPERATION_COUNT.
    public static readonly ESTRUCTURAL_FEATURE_OPERATION_COUNT: number = 2
    
    // EATTRIBUTE is the meta object id for the class EAttribute.
    public static readonly EATTRIBUTE: number = 53
    
    // EATTRIBUTE__EANNOTATIONS is the feature id for the EAttribute 'EAnnotations' containment reference list.
    public static readonly EATTRIBUTE__EANNOTATIONS: number = 0
    
    // EATTRIBUTE__NAME is the feature id for the EAttribute 'Name' attribute.
    public static readonly EATTRIBUTE__NAME: number = 1
    
    // EATTRIBUTE__ORDERED is the feature id for the EAttribute 'IsOrdered' attribute.
    public static readonly EATTRIBUTE__ORDERED: number = 2
    
    // EATTRIBUTE__UNIQUE is the feature id for the EAttribute 'IsUnique' attribute.
    public static readonly EATTRIBUTE__UNIQUE: number = 3
    
    // EATTRIBUTE__LOWER_BOUND is the feature id for the EAttribute 'LowerBound' attribute.
    public static readonly EATTRIBUTE__LOWER_BOUND: number = 4
    
    // EATTRIBUTE__UPPER_BOUND is the feature id for the EAttribute 'UpperBound' attribute.
    public static readonly EATTRIBUTE__UPPER_BOUND: number = 5
    
    // EATTRIBUTE__MANY is the feature id for the EAttribute 'IsMany' attribute.
    public static readonly EATTRIBUTE__MANY: number = 6
    
    // EATTRIBUTE__REQUIRED is the feature id for the EAttribute 'IsRequired' attribute.
    public static readonly EATTRIBUTE__REQUIRED: number = 7
    
    // EATTRIBUTE__ETYPE is the feature id for the EAttribute 'EType' reference.
    public static readonly EATTRIBUTE__ETYPE: number = 8
    
    // EATTRIBUTE__CHANGEABLE is the feature id for the EAttribute 'IsChangeable' attribute.
    public static readonly EATTRIBUTE__CHANGEABLE: number = 9
    
    // EATTRIBUTE__VOLATILE is the feature id for the EAttribute 'IsVolatile' attribute.
    public static readonly EATTRIBUTE__VOLATILE: number = 10
    
    // EATTRIBUTE__TRANSIENT is the feature id for the EAttribute 'IsTransient' attribute.
    public static readonly EATTRIBUTE__TRANSIENT: number = 11
    
    // EATTRIBUTE__DEFAULT_VALUE_LITERAL is the feature id for the EAttribute 'DefaultValueLiteral' attribute.
    public static readonly EATTRIBUTE__DEFAULT_VALUE_LITERAL: number = 12
    
    // EATTRIBUTE__DEFAULT_VALUE is the feature id for the EAttribute 'DefaultValue' attribute.
    public static readonly EATTRIBUTE__DEFAULT_VALUE: number = 13
    
    // EATTRIBUTE__UNSETTABLE is the feature id for the EAttribute 'IsUnsettable' attribute.
    public static readonly EATTRIBUTE__UNSETTABLE: number = 14
    
    // EATTRIBUTE__DERIVED is the feature id for the EAttribute 'IsDerived' attribute.
    public static readonly EATTRIBUTE__DERIVED: number = 15
    
    // EATTRIBUTE__ECONTAINING_CLASS is the feature id for the EAttribute 'EContainingClass' container reference.
    public static readonly EATTRIBUTE__ECONTAINING_CLASS: number = 16
    
    // EATTRIBUTE__FEATURE_ID is the feature id for the EAttribute 'FeatureID' attribute.
    public static readonly EATTRIBUTE__FEATURE_ID: number = 17
    
    // EATTRIBUTE__ID is the feature id for the EAttribute 'IsID' attribute.
    public static readonly EATTRIBUTE__ID: number = 18
    
    // EATTRIBUTE__EATTRIBUTE_TYPE is the feature id for the EAttribute 'EAttributeType' reference.
    public static readonly EATTRIBUTE__EATTRIBUTE_TYPE: number = 19
    
    
    // EATTRIBUTE_FEATURE_COUNT is the number of structural features of the class EAttribute.
    public static readonly EATTRIBUTE_FEATURE_COUNT: number = 20
    
    // EATTRIBUTE__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly EATTRIBUTE__GET_EANNOTATION_ESTRING: number = 0
    // EATTRIBUTE__GET_CONTAINER_CLASS is the operation id for the 'getContainerClass' operation.
    public static readonly EATTRIBUTE__GET_CONTAINER_CLASS: number = 1
    
    // EATTRIBUTE_OPERATION_COUNT is the number of EATTRIBUTE_OPERATION_COUNT.
    public static readonly EATTRIBUTE_OPERATION_COUNT: number = 2
    
    // EANNOTATION is the meta object id for the class EAnnotation.
    public static readonly EANNOTATION: number = 1
    
    // EANNOTATION__EANNOTATIONS is the feature id for the EAnnotation 'EAnnotations' containment reference list.
    public static readonly EANNOTATION__EANNOTATIONS: number = 0
    
    // EANNOTATION__SOURCE is the feature id for the EAnnotation 'Source' attribute.
    public static readonly EANNOTATION__SOURCE: number = 1
    
    // EANNOTATION__DETAILS is the feature id for the EAnnotation 'Details' map.
    public static readonly EANNOTATION__DETAILS: number = 2
    
    // EANNOTATION__EMODEL_ELEMENT is the feature id for the EAnnotation 'EModelElement' container reference.
    public static readonly EANNOTATION__EMODEL_ELEMENT: number = 3
    
    // EANNOTATION__CONTENTS is the feature id for the EAnnotation 'Contents' containment reference list.
    public static readonly EANNOTATION__CONTENTS: number = 4
    
    // EANNOTATION__REFERENCES is the feature id for the EAnnotation 'References' reference list.
    public static readonly EANNOTATION__REFERENCES: number = 5
    
    
    // EANNOTATION_FEATURE_COUNT is the number of structural features of the class EAnnotation.
    public static readonly EANNOTATION_FEATURE_COUNT: number = 6
    
    // EANNOTATION__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly EANNOTATION__GET_EANNOTATION_ESTRING: number = 0
    
    // EANNOTATION_OPERATION_COUNT is the number of EANNOTATION_OPERATION_COUNT.
    public static readonly EANNOTATION_OPERATION_COUNT: number = 1
    
    // ECLASSIFIER is the meta object id for the class EClassifier.
    public static readonly ECLASSIFIER: number = 3
    
    // ECLASSIFIER__EANNOTATIONS is the feature id for the EClassifier 'EAnnotations' containment reference list.
    public static readonly ECLASSIFIER__EANNOTATIONS: number = 0
    
    // ECLASSIFIER__NAME is the feature id for the EClassifier 'Name' attribute.
    public static readonly ECLASSIFIER__NAME: number = 1
    
    // ECLASSIFIER__INSTANCE_CLASS_NAME is the feature id for the EClassifier 'InstanceClassName' attribute.
    public static readonly ECLASSIFIER__INSTANCE_CLASS_NAME: number = 2
    
    // ECLASSIFIER__INSTANCE_CLASS is the feature id for the EClassifier 'InstanceClass' attribute.
    public static readonly ECLASSIFIER__INSTANCE_CLASS: number = 3
    
    // ECLASSIFIER__INSTANCE_TYPE_NAME is the feature id for the EClassifier 'InstanceTypeName' attribute.
    public static readonly ECLASSIFIER__INSTANCE_TYPE_NAME: number = 4
    
    // ECLASSIFIER__DEFAULT_VALUE is the feature id for the EClassifier 'DefaultValue' attribute.
    public static readonly ECLASSIFIER__DEFAULT_VALUE: number = 5
    
    // ECLASSIFIER__EPACKAGE is the feature id for the EClassifier 'EPackage' container reference.
    public static readonly ECLASSIFIER__EPACKAGE: number = 6
    
    // ECLASSIFIER__CLASSIFIER_ID is the feature id for the EClassifier 'ClassifierID' attribute.
    public static readonly ECLASSIFIER__CLASSIFIER_ID: number = 7
    
    
    // ECLASSIFIER_FEATURE_COUNT is the number of structural features of the class EClassifier.
    public static readonly ECLASSIFIER_FEATURE_COUNT: number = 8
    
    // ECLASSIFIER__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly ECLASSIFIER__GET_EANNOTATION_ESTRING: number = 0
    // ECLASSIFIER__IS_INSTANCE_EJAVAOBJECT is the operation id for the 'isInstance' operation.
    public static readonly ECLASSIFIER__IS_INSTANCE_EJAVAOBJECT: number = 1
    
    // ECLASSIFIER_OPERATION_COUNT is the number of ECLASSIFIER_OPERATION_COUNT.
    public static readonly ECLASSIFIER_OPERATION_COUNT: number = 2
    
    // ECLASS is the meta object id for the class EClass.
    public static readonly ECLASS: number = 2
    
    // ECLASS__EANNOTATIONS is the feature id for the EClass 'EAnnotations' containment reference list.
    public static readonly ECLASS__EANNOTATIONS: number = 0
    
    // ECLASS__NAME is the feature id for the EClass 'Name' attribute.
    public static readonly ECLASS__NAME: number = 1
    
    // ECLASS__INSTANCE_CLASS_NAME is the feature id for the EClass 'InstanceClassName' attribute.
    public static readonly ECLASS__INSTANCE_CLASS_NAME: number = 2
    
    // ECLASS__INSTANCE_CLASS is the feature id for the EClass 'InstanceClass' attribute.
    public static readonly ECLASS__INSTANCE_CLASS: number = 3
    
    // ECLASS__INSTANCE_TYPE_NAME is the feature id for the EClass 'InstanceTypeName' attribute.
    public static readonly ECLASS__INSTANCE_TYPE_NAME: number = 4
    
    // ECLASS__DEFAULT_VALUE is the feature id for the EClass 'DefaultValue' attribute.
    public static readonly ECLASS__DEFAULT_VALUE: number = 5
    
    // ECLASS__EPACKAGE is the feature id for the EClass 'EPackage' container reference.
    public static readonly ECLASS__EPACKAGE: number = 6
    
    // ECLASS__CLASSIFIER_ID is the feature id for the EClass 'ClassifierID' attribute.
    public static readonly ECLASS__CLASSIFIER_ID: number = 7
    
    // ECLASS__ABSTRACT is the feature id for the EClass 'IsAbstract' attribute.
    public static readonly ECLASS__ABSTRACT: number = 8
    
    // ECLASS__INTERFACE is the feature id for the EClass 'IsInterface' attribute.
    public static readonly ECLASS__INTERFACE: number = 9
    
    // ECLASS__ESTRUCTURAL_FEATURES is the feature id for the EClass 'EStructuralFeatures' containment reference list.
    public static readonly ECLASS__ESTRUCTURAL_FEATURES: number = 10
    
    // ECLASS__EATTRIBUTES is the feature id for the EClass 'EAttributes' reference list.
    public static readonly ECLASS__EATTRIBUTES: number = 11
    
    // ECLASS__EREFERENCES is the feature id for the EClass 'EReferences' reference list.
    public static readonly ECLASS__EREFERENCES: number = 12
    
    // ECLASS__ESUPER_TYPES is the feature id for the EClass 'ESuperTypes' reference list.
    public static readonly ECLASS__ESUPER_TYPES: number = 13
    
    // ECLASS__EOPERATIONS is the feature id for the EClass 'EOperations' containment reference list.
    public static readonly ECLASS__EOPERATIONS: number = 14
    
    // ECLASS__ECONTAINMENT_FEATURES is the feature id for the EClass 'EContainmentFeatures' reference list.
    public static readonly ECLASS__ECONTAINMENT_FEATURES: number = 15
    
    // ECLASS__ECROSS_REFERENCE_FEATURES is the feature id for the EClass 'ECrossReferenceFeatures' reference list.
    public static readonly ECLASS__ECROSS_REFERENCE_FEATURES: number = 16
    
    // ECLASS__EALL_ATTRIBUTES is the feature id for the EClass 'EAllAttributes' reference list.
    public static readonly ECLASS__EALL_ATTRIBUTES: number = 17
    
    // ECLASS__EALL_REFERENCES is the feature id for the EClass 'EAllReferences' reference list.
    public static readonly ECLASS__EALL_REFERENCES: number = 18
    
    // ECLASS__EALL_CONTAINMENTS is the feature id for the EClass 'EAllContainments' reference list.
    public static readonly ECLASS__EALL_CONTAINMENTS: number = 19
    
    // ECLASS__EALL_CROSS_REFERENCES is the feature id for the EClass 'EAllCrossReferences' reference list.
    public static readonly ECLASS__EALL_CROSS_REFERENCES: number = 20
    
    // ECLASS__EALL_OPERATIONS is the feature id for the EClass 'EAllOperations' reference list.
    public static readonly ECLASS__EALL_OPERATIONS: number = 21
    
    // ECLASS__EALL_STRUCTURAL_FEATURES is the feature id for the EClass 'EAllStructuralFeatures' reference list.
    public static readonly ECLASS__EALL_STRUCTURAL_FEATURES: number = 22
    
    // ECLASS__EALL_SUPER_TYPES is the feature id for the EClass 'EAllSuperTypes' reference list.
    public static readonly ECLASS__EALL_SUPER_TYPES: number = 23
    
    // ECLASS__EID_ATTRIBUTE is the feature id for the EClass 'EIDAttribute' reference.
    public static readonly ECLASS__EID_ATTRIBUTE: number = 24
    
    
    // ECLASS_FEATURE_COUNT is the number of structural features of the class EClass.
    public static readonly ECLASS_FEATURE_COUNT: number = 25
    
    // ECLASS__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly ECLASS__GET_EANNOTATION_ESTRING: number = 0
    // ECLASS__IS_INSTANCE_EJAVAOBJECT is the operation id for the 'isInstance' operation.
    public static readonly ECLASS__IS_INSTANCE_EJAVAOBJECT: number = 1
    // ECLASS__IS_SUPER_TYPE_OF_ECLASS is the operation id for the 'isSuperTypeOf' operation.
    public static readonly ECLASS__IS_SUPER_TYPE_OF_ECLASS: number = 2
    // ECLASS__GET_FEATURE_COUNT is the operation id for the 'getFeatureCount' operation.
    public static readonly ECLASS__GET_FEATURE_COUNT: number = 3
    // ECLASS__GET_ESTRUCTURAL_FEATURE_EINT is the operation id for the 'getEStructuralFeature' operation.
    public static readonly ECLASS__GET_ESTRUCTURAL_FEATURE_EINT: number = 4
    // ECLASS__GET_ESTRUCTURAL_FEATURE_ESTRING is the operation id for the 'getEStructuralFeature' operation.
    public static readonly ECLASS__GET_ESTRUCTURAL_FEATURE_ESTRING: number = 5
    // ECLASS__GET_FEATURE_ID_ESTRUCTURALFEATURE is the operation id for the 'getFeatureID' operation.
    public static readonly ECLASS__GET_FEATURE_ID_ESTRUCTURALFEATURE: number = 6
    // ECLASS__GET_OPERATION_COUNT is the operation id for the 'getOperationCount' operation.
    public static readonly ECLASS__GET_OPERATION_COUNT: number = 7
    // ECLASS__GET_EOPERATION_EINT is the operation id for the 'getEOperation' operation.
    public static readonly ECLASS__GET_EOPERATION_EINT: number = 8
    // ECLASS__GET_OPERATION_ID_EOPERATION is the operation id for the 'getOperationID' operation.
    public static readonly ECLASS__GET_OPERATION_ID_EOPERATION: number = 9
    // ECLASS__GET_OVERRIDE_EOPERATION is the operation id for the 'getOverride' operation.
    public static readonly ECLASS__GET_OVERRIDE_EOPERATION: number = 10
    // ECLASS__GET_FEATURE_TYPE_ESTRUCTURALFEATURE is the operation id for the 'getFeatureType' operation.
    public static readonly ECLASS__GET_FEATURE_TYPE_ESTRUCTURALFEATURE: number = 11
    
    // ECLASS_OPERATION_COUNT is the number of ECLASS_OPERATION_COUNT.
    public static readonly ECLASS_OPERATION_COUNT: number = 12
    
    // EDATA_TYPE is the meta object id for the class EDataType.
    public static readonly EDATA_TYPE: number = 4
    
    // EDATA_TYPE__EANNOTATIONS is the feature id for the EDataType 'EAnnotations' containment reference list.
    public static readonly EDATA_TYPE__EANNOTATIONS: number = 0
    
    // EDATA_TYPE__NAME is the feature id for the EDataType 'Name' attribute.
    public static readonly EDATA_TYPE__NAME: number = 1
    
    // EDATA_TYPE__INSTANCE_CLASS_NAME is the feature id for the EDataType 'InstanceClassName' attribute.
    public static readonly EDATA_TYPE__INSTANCE_CLASS_NAME: number = 2
    
    // EDATA_TYPE__INSTANCE_CLASS is the feature id for the EDataType 'InstanceClass' attribute.
    public static readonly EDATA_TYPE__INSTANCE_CLASS: number = 3
    
    // EDATA_TYPE__INSTANCE_TYPE_NAME is the feature id for the EDataType 'InstanceTypeName' attribute.
    public static readonly EDATA_TYPE__INSTANCE_TYPE_NAME: number = 4
    
    // EDATA_TYPE__DEFAULT_VALUE is the feature id for the EDataType 'DefaultValue' attribute.
    public static readonly EDATA_TYPE__DEFAULT_VALUE: number = 5
    
    // EDATA_TYPE__EPACKAGE is the feature id for the EDataType 'EPackage' container reference.
    public static readonly EDATA_TYPE__EPACKAGE: number = 6
    
    // EDATA_TYPE__CLASSIFIER_ID is the feature id for the EDataType 'ClassifierID' attribute.
    public static readonly EDATA_TYPE__CLASSIFIER_ID: number = 7
    
    // EDATA_TYPE__SERIALIZABLE is the feature id for the EDataType 'IsSerializable' attribute.
    public static readonly EDATA_TYPE__SERIALIZABLE: number = 8
    
    
    // EDATA_TYPE_FEATURE_COUNT is the number of structural features of the class EDataType.
    public static readonly EDATA_TYPE_FEATURE_COUNT: number = 9
    
    // EDATA_TYPE__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly EDATA_TYPE__GET_EANNOTATION_ESTRING: number = 0
    // EDATA_TYPE__IS_INSTANCE_EJAVAOBJECT is the operation id for the 'isInstance' operation.
    public static readonly EDATA_TYPE__IS_INSTANCE_EJAVAOBJECT: number = 1
    
    // EDATA_TYPE_OPERATION_COUNT is the number of EDATA_TYPE_OPERATION_COUNT.
    public static readonly EDATA_TYPE_OPERATION_COUNT: number = 2
    
    // EENUM is the meta object id for the class EEnum.
    public static readonly EENUM: number = 5
    
    // EENUM__EANNOTATIONS is the feature id for the EEnum 'EAnnotations' containment reference list.
    public static readonly EENUM__EANNOTATIONS: number = 0
    
    // EENUM__NAME is the feature id for the EEnum 'Name' attribute.
    public static readonly EENUM__NAME: number = 1
    
    // EENUM__INSTANCE_CLASS_NAME is the feature id for the EEnum 'InstanceClassName' attribute.
    public static readonly EENUM__INSTANCE_CLASS_NAME: number = 2
    
    // EENUM__INSTANCE_CLASS is the feature id for the EEnum 'InstanceClass' attribute.
    public static readonly EENUM__INSTANCE_CLASS: number = 3
    
    // EENUM__INSTANCE_TYPE_NAME is the feature id for the EEnum 'InstanceTypeName' attribute.
    public static readonly EENUM__INSTANCE_TYPE_NAME: number = 4
    
    // EENUM__DEFAULT_VALUE is the feature id for the EEnum 'DefaultValue' attribute.
    public static readonly EENUM__DEFAULT_VALUE: number = 5
    
    // EENUM__EPACKAGE is the feature id for the EEnum 'EPackage' container reference.
    public static readonly EENUM__EPACKAGE: number = 6
    
    // EENUM__CLASSIFIER_ID is the feature id for the EEnum 'ClassifierID' attribute.
    public static readonly EENUM__CLASSIFIER_ID: number = 7
    
    // EENUM__SERIALIZABLE is the feature id for the EEnum 'IsSerializable' attribute.
    public static readonly EENUM__SERIALIZABLE: number = 8
    
    // EENUM__ELITERALS is the feature id for the EEnum 'ELiterals' containment reference list.
    public static readonly EENUM__ELITERALS: number = 9
    
    
    // EENUM_FEATURE_COUNT is the number of structural features of the class EEnum.
    public static readonly EENUM_FEATURE_COUNT: number = 10
    
    // EENUM__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly EENUM__GET_EANNOTATION_ESTRING: number = 0
    // EENUM__IS_INSTANCE_EJAVAOBJECT is the operation id for the 'isInstance' operation.
    public static readonly EENUM__IS_INSTANCE_EJAVAOBJECT: number = 1
    // EENUM__GET_EENUM_LITERAL_ESTRING is the operation id for the 'getEEnumLiteral' operation.
    public static readonly EENUM__GET_EENUM_LITERAL_ESTRING: number = 2
    // EENUM__GET_EENUM_LITERAL_EINT is the operation id for the 'getEEnumLiteral' operation.
    public static readonly EENUM__GET_EENUM_LITERAL_EINT: number = 3
    // EENUM__GET_EENUM_LITERAL_BY_LITERAL_ESTRING is the operation id for the 'getEEnumLiteralByLiteral' operation.
    public static readonly EENUM__GET_EENUM_LITERAL_BY_LITERAL_ESTRING: number = 4
    
    // EENUM_OPERATION_COUNT is the number of EENUM_OPERATION_COUNT.
    public static readonly EENUM_OPERATION_COUNT: number = 5
    
    // EENUM_LITERAL is the meta object id for the class EEnumLiteral.
    public static readonly EENUM_LITERAL: number = 6
    
    // EENUM_LITERAL__EANNOTATIONS is the feature id for the EEnumLiteral 'EAnnotations' containment reference list.
    public static readonly EENUM_LITERAL__EANNOTATIONS: number = 0
    
    // EENUM_LITERAL__NAME is the feature id for the EEnumLiteral 'Name' attribute.
    public static readonly EENUM_LITERAL__NAME: number = 1
    
    // EENUM_LITERAL__VALUE is the feature id for the EEnumLiteral 'Value' attribute.
    public static readonly EENUM_LITERAL__VALUE: number = 2
    
    // EENUM_LITERAL__INSTANCE is the feature id for the EEnumLiteral 'Instance' attribute.
    public static readonly EENUM_LITERAL__INSTANCE: number = 3
    
    // EENUM_LITERAL__LITERAL is the feature id for the EEnumLiteral 'Literal' attribute.
    public static readonly EENUM_LITERAL__LITERAL: number = 4
    
    // EENUM_LITERAL__EENUM is the feature id for the EEnumLiteral 'EEnum' container reference.
    public static readonly EENUM_LITERAL__EENUM: number = 5
    
    
    // EENUM_LITERAL_FEATURE_COUNT is the number of structural features of the class EEnumLiteral.
    public static readonly EENUM_LITERAL_FEATURE_COUNT: number = 6
    
    // EENUM_LITERAL__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly EENUM_LITERAL__GET_EANNOTATION_ESTRING: number = 0
    
    // EENUM_LITERAL_OPERATION_COUNT is the number of EENUM_LITERAL_OPERATION_COUNT.
    public static readonly EENUM_LITERAL_OPERATION_COUNT: number = 1
    
    // EFACTORY is the meta object id for the class EFactory.
    public static readonly EFACTORY: number = 7
    
    // EFACTORY__EANNOTATIONS is the feature id for the EFactory 'EAnnotations' containment reference list.
    public static readonly EFACTORY__EANNOTATIONS: number = 0
    
    // EFACTORY__EPACKAGE is the feature id for the EFactory 'EPackage' container reference.
    public static readonly EFACTORY__EPACKAGE: number = 1
    
    
    // EFACTORY_FEATURE_COUNT is the number of structural features of the class EFactory.
    public static readonly EFACTORY_FEATURE_COUNT: number = 2
    
    // EFACTORY__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly EFACTORY__GET_EANNOTATION_ESTRING: number = 0
    // EFACTORY__CREATE_ECLASS is the operation id for the 'create' operation.
    public static readonly EFACTORY__CREATE_ECLASS: number = 1
    // EFACTORY__CREATE_FROM_STRING_EDATATYPE_ESTRING is the operation id for the 'createFromString' operation.
    public static readonly EFACTORY__CREATE_FROM_STRING_EDATATYPE_ESTRING: number = 2
    // EFACTORY__CONVERT_TO_STRING_EDATATYPE_EJAVAOBJECT is the operation id for the 'convertToString' operation.
    public static readonly EFACTORY__CONVERT_TO_STRING_EDATATYPE_EJAVAOBJECT: number = 3
    
    // EFACTORY_OPERATION_COUNT is the number of EFACTORY_OPERATION_COUNT.
    public static readonly EFACTORY_OPERATION_COUNT: number = 4
    
    // EOBJECT is the meta object id for the class EObject.
    public static readonly EOBJECT: number = 10
    
    
    // EOBJECT_FEATURE_COUNT is the number of structural features of the class EObject.
    public static readonly EOBJECT_FEATURE_COUNT: number = 0
    
    // EOBJECT__ECLASS is the operation id for the 'eClass' operation.
    public static readonly EOBJECT__ECLASS: number = 0
    // EOBJECT__EIS_PROXY is the operation id for the 'eIsProxy' operation.
    public static readonly EOBJECT__EIS_PROXY: number = 1
    // EOBJECT__ERESOURCE is the operation id for the 'eResource' operation.
    public static readonly EOBJECT__ERESOURCE: number = 2
    // EOBJECT__ECONTAINER is the operation id for the 'eContainer' operation.
    public static readonly EOBJECT__ECONTAINER: number = 3
    // EOBJECT__ECONTAINING_FEATURE is the operation id for the 'eContainingFeature' operation.
    public static readonly EOBJECT__ECONTAINING_FEATURE: number = 4
    // EOBJECT__ECONTAINMENT_FEATURE is the operation id for the 'eContainmentFeature' operation.
    public static readonly EOBJECT__ECONTAINMENT_FEATURE: number = 5
    // EOBJECT__ECONTENTS is the operation id for the 'eContents' operation.
    public static readonly EOBJECT__ECONTENTS: number = 6
    // EOBJECT__EALL_CONTENTS is the operation id for the 'eAllContents' operation.
    public static readonly EOBJECT__EALL_CONTENTS: number = 7
    // EOBJECT__ECROSS_REFERENCES is the operation id for the 'eCrossReferences' operation.
    public static readonly EOBJECT__ECROSS_REFERENCES: number = 8
    // EOBJECT__EGET_ESTRUCTURALFEATURE is the operation id for the 'eGet' operation.
    public static readonly EOBJECT__EGET_ESTRUCTURALFEATURE: number = 9
    // EOBJECT__EGET_ESTRUCTURALFEATURE_EBOOLEAN is the operation id for the 'eGet' operation.
    public static readonly EOBJECT__EGET_ESTRUCTURALFEATURE_EBOOLEAN: number = 10
    // EOBJECT__ESET_ESTRUCTURALFEATURE_EJAVAOBJECT is the operation id for the 'eSet' operation.
    public static readonly EOBJECT__ESET_ESTRUCTURALFEATURE_EJAVAOBJECT: number = 11
    // EOBJECT__EIS_SET_ESTRUCTURALFEATURE is the operation id for the 'eIsSet' operation.
    public static readonly EOBJECT__EIS_SET_ESTRUCTURALFEATURE: number = 12
    // EOBJECT__EUNSET_ESTRUCTURALFEATURE is the operation id for the 'eUnset' operation.
    public static readonly EOBJECT__EUNSET_ESTRUCTURALFEATURE: number = 13
    // EOBJECT__EINVOKE_EOPERATION_EELIST is the operation id for the 'eInvoke' operation.
    public static readonly EOBJECT__EINVOKE_EOPERATION_EELIST: number = 14
    
    // EOBJECT_OPERATION_COUNT is the number of EOBJECT_OPERATION_COUNT.
    public static readonly EOBJECT_OPERATION_COUNT: number = 15
    
    // EOPERATION is the meta object id for the class EOperation.
    public static readonly EOPERATION: number = 11
    
    // EOPERATION__EANNOTATIONS is the feature id for the EOperation 'EAnnotations' containment reference list.
    public static readonly EOPERATION__EANNOTATIONS: number = 0
    
    // EOPERATION__NAME is the feature id for the EOperation 'Name' attribute.
    public static readonly EOPERATION__NAME: number = 1
    
    // EOPERATION__ORDERED is the feature id for the EOperation 'IsOrdered' attribute.
    public static readonly EOPERATION__ORDERED: number = 2
    
    // EOPERATION__UNIQUE is the feature id for the EOperation 'IsUnique' attribute.
    public static readonly EOPERATION__UNIQUE: number = 3
    
    // EOPERATION__LOWER_BOUND is the feature id for the EOperation 'LowerBound' attribute.
    public static readonly EOPERATION__LOWER_BOUND: number = 4
    
    // EOPERATION__UPPER_BOUND is the feature id for the EOperation 'UpperBound' attribute.
    public static readonly EOPERATION__UPPER_BOUND: number = 5
    
    // EOPERATION__MANY is the feature id for the EOperation 'IsMany' attribute.
    public static readonly EOPERATION__MANY: number = 6
    
    // EOPERATION__REQUIRED is the feature id for the EOperation 'IsRequired' attribute.
    public static readonly EOPERATION__REQUIRED: number = 7
    
    // EOPERATION__ETYPE is the feature id for the EOperation 'EType' reference.
    public static readonly EOPERATION__ETYPE: number = 8
    
    // EOPERATION__ECONTAINING_CLASS is the feature id for the EOperation 'EContainingClass' container reference.
    public static readonly EOPERATION__ECONTAINING_CLASS: number = 9
    
    // EOPERATION__EPARAMETERS is the feature id for the EOperation 'EParameters' containment reference list.
    public static readonly EOPERATION__EPARAMETERS: number = 10
    
    // EOPERATION__EEXCEPTIONS is the feature id for the EOperation 'EExceptions' reference list.
    public static readonly EOPERATION__EEXCEPTIONS: number = 11
    
    // EOPERATION__OPERATION_ID is the feature id for the EOperation 'OperationID' attribute.
    public static readonly EOPERATION__OPERATION_ID: number = 12
    
    
    // EOPERATION_FEATURE_COUNT is the number of structural features of the class EOperation.
    public static readonly EOPERATION_FEATURE_COUNT: number = 13
    
    // EOPERATION__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly EOPERATION__GET_EANNOTATION_ESTRING: number = 0
    // EOPERATION__IS_OVERRIDE_OF_EOPERATION is the operation id for the 'isOverrideOf' operation.
    public static readonly EOPERATION__IS_OVERRIDE_OF_EOPERATION: number = 1
    
    // EOPERATION_OPERATION_COUNT is the number of EOPERATION_OPERATION_COUNT.
    public static readonly EOPERATION_OPERATION_COUNT: number = 2
    
    // EPACKAGE is the meta object id for the class EPackage.
    public static readonly EPACKAGE: number = 12
    
    // EPACKAGE__EANNOTATIONS is the feature id for the EPackage 'EAnnotations' containment reference list.
    public static readonly EPACKAGE__EANNOTATIONS: number = 0
    
    // EPACKAGE__NAME is the feature id for the EPackage 'Name' attribute.
    public static readonly EPACKAGE__NAME: number = 1
    
    // EPACKAGE__NS_URI is the feature id for the EPackage 'NsURI' attribute.
    public static readonly EPACKAGE__NS_URI: number = 2
    
    // EPACKAGE__NS_PREFIX is the feature id for the EPackage 'NsPrefix' attribute.
    public static readonly EPACKAGE__NS_PREFIX: number = 3
    
    // EPACKAGE__EFACTORY_INSTANCE is the feature id for the EPackage 'EFactoryInstance' containment reference.
    public static readonly EPACKAGE__EFACTORY_INSTANCE: number = 4
    
    // EPACKAGE__ECLASSIFIERS is the feature id for the EPackage 'EClassifiers' containment reference list.
    public static readonly EPACKAGE__ECLASSIFIERS: number = 5
    
    // EPACKAGE__ESUB_PACKAGES is the feature id for the EPackage 'ESubPackages' containment reference list.
    public static readonly EPACKAGE__ESUB_PACKAGES: number = 6
    
    // EPACKAGE__ESUPER_PACKAGE is the feature id for the EPackage 'ESuperPackage' container reference.
    public static readonly EPACKAGE__ESUPER_PACKAGE: number = 7
    
    
    // EPACKAGE_FEATURE_COUNT is the number of structural features of the class EPackage.
    public static readonly EPACKAGE_FEATURE_COUNT: number = 8
    
    // EPACKAGE__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly EPACKAGE__GET_EANNOTATION_ESTRING: number = 0
    // EPACKAGE__GET_ECLASSIFIER_ESTRING is the operation id for the 'getEClassifier' operation.
    public static readonly EPACKAGE__GET_ECLASSIFIER_ESTRING: number = 1
    
    // EPACKAGE_OPERATION_COUNT is the number of EPACKAGE_OPERATION_COUNT.
    public static readonly EPACKAGE_OPERATION_COUNT: number = 2
    
    // EPARAMETER is the meta object id for the class EParameter.
    public static readonly EPARAMETER: number = 13
    
    // EPARAMETER__EANNOTATIONS is the feature id for the EParameter 'EAnnotations' containment reference list.
    public static readonly EPARAMETER__EANNOTATIONS: number = 0
    
    // EPARAMETER__NAME is the feature id for the EParameter 'Name' attribute.
    public static readonly EPARAMETER__NAME: number = 1
    
    // EPARAMETER__ORDERED is the feature id for the EParameter 'IsOrdered' attribute.
    public static readonly EPARAMETER__ORDERED: number = 2
    
    // EPARAMETER__UNIQUE is the feature id for the EParameter 'IsUnique' attribute.
    public static readonly EPARAMETER__UNIQUE: number = 3
    
    // EPARAMETER__LOWER_BOUND is the feature id for the EParameter 'LowerBound' attribute.
    public static readonly EPARAMETER__LOWER_BOUND: number = 4
    
    // EPARAMETER__UPPER_BOUND is the feature id for the EParameter 'UpperBound' attribute.
    public static readonly EPARAMETER__UPPER_BOUND: number = 5
    
    // EPARAMETER__MANY is the feature id for the EParameter 'IsMany' attribute.
    public static readonly EPARAMETER__MANY: number = 6
    
    // EPARAMETER__REQUIRED is the feature id for the EParameter 'IsRequired' attribute.
    public static readonly EPARAMETER__REQUIRED: number = 7
    
    // EPARAMETER__ETYPE is the feature id for the EParameter 'EType' reference.
    public static readonly EPARAMETER__ETYPE: number = 8
    
    // EPARAMETER__EOPERATION is the feature id for the EParameter 'EOperation' container reference.
    public static readonly EPARAMETER__EOPERATION: number = 9
    
    
    // EPARAMETER_FEATURE_COUNT is the number of structural features of the class EParameter.
    public static readonly EPARAMETER_FEATURE_COUNT: number = 10
    
    // EPARAMETER__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly EPARAMETER__GET_EANNOTATION_ESTRING: number = 0
    
    // EPARAMETER_OPERATION_COUNT is the number of EPARAMETER_OPERATION_COUNT.
    public static readonly EPARAMETER_OPERATION_COUNT: number = 1
    
    // EREFERENCE is the meta object id for the class EReference.
    public static readonly EREFERENCE: number = 14
    
    // EREFERENCE__EANNOTATIONS is the feature id for the EReference 'EAnnotations' containment reference list.
    public static readonly EREFERENCE__EANNOTATIONS: number = 0
    
    // EREFERENCE__NAME is the feature id for the EReference 'Name' attribute.
    public static readonly EREFERENCE__NAME: number = 1
    
    // EREFERENCE__ORDERED is the feature id for the EReference 'IsOrdered' attribute.
    public static readonly EREFERENCE__ORDERED: number = 2
    
    // EREFERENCE__UNIQUE is the feature id for the EReference 'IsUnique' attribute.
    public static readonly EREFERENCE__UNIQUE: number = 3
    
    // EREFERENCE__LOWER_BOUND is the feature id for the EReference 'LowerBound' attribute.
    public static readonly EREFERENCE__LOWER_BOUND: number = 4
    
    // EREFERENCE__UPPER_BOUND is the feature id for the EReference 'UpperBound' attribute.
    public static readonly EREFERENCE__UPPER_BOUND: number = 5
    
    // EREFERENCE__MANY is the feature id for the EReference 'IsMany' attribute.
    public static readonly EREFERENCE__MANY: number = 6
    
    // EREFERENCE__REQUIRED is the feature id for the EReference 'IsRequired' attribute.
    public static readonly EREFERENCE__REQUIRED: number = 7
    
    // EREFERENCE__ETYPE is the feature id for the EReference 'EType' reference.
    public static readonly EREFERENCE__ETYPE: number = 8
    
    // EREFERENCE__CHANGEABLE is the feature id for the EReference 'IsChangeable' attribute.
    public static readonly EREFERENCE__CHANGEABLE: number = 9
    
    // EREFERENCE__VOLATILE is the feature id for the EReference 'IsVolatile' attribute.
    public static readonly EREFERENCE__VOLATILE: number = 10
    
    // EREFERENCE__TRANSIENT is the feature id for the EReference 'IsTransient' attribute.
    public static readonly EREFERENCE__TRANSIENT: number = 11
    
    // EREFERENCE__DEFAULT_VALUE_LITERAL is the feature id for the EReference 'DefaultValueLiteral' attribute.
    public static readonly EREFERENCE__DEFAULT_VALUE_LITERAL: number = 12
    
    // EREFERENCE__DEFAULT_VALUE is the feature id for the EReference 'DefaultValue' attribute.
    public static readonly EREFERENCE__DEFAULT_VALUE: number = 13
    
    // EREFERENCE__UNSETTABLE is the feature id for the EReference 'IsUnsettable' attribute.
    public static readonly EREFERENCE__UNSETTABLE: number = 14
    
    // EREFERENCE__DERIVED is the feature id for the EReference 'IsDerived' attribute.
    public static readonly EREFERENCE__DERIVED: number = 15
    
    // EREFERENCE__ECONTAINING_CLASS is the feature id for the EReference 'EContainingClass' container reference.
    public static readonly EREFERENCE__ECONTAINING_CLASS: number = 16
    
    // EREFERENCE__FEATURE_ID is the feature id for the EReference 'FeatureID' attribute.
    public static readonly EREFERENCE__FEATURE_ID: number = 17
    
    // EREFERENCE__CONTAINMENT is the feature id for the EReference 'IsContainment' attribute.
    public static readonly EREFERENCE__CONTAINMENT: number = 18
    
    // EREFERENCE__CONTAINER is the feature id for the EReference 'IsContainer' attribute.
    public static readonly EREFERENCE__CONTAINER: number = 19
    
    // EREFERENCE__RESOLVE_PROXIES is the feature id for the EReference 'IsResolveProxies' attribute.
    public static readonly EREFERENCE__RESOLVE_PROXIES: number = 20
    
    // EREFERENCE__EOPPOSITE is the feature id for the EReference 'EOpposite' reference.
    public static readonly EREFERENCE__EOPPOSITE: number = 21
    
    // EREFERENCE__EREFERENCE_TYPE is the feature id for the EReference 'EReferenceType' reference.
    public static readonly EREFERENCE__EREFERENCE_TYPE: number = 22
    
    // EREFERENCE__EKEYS is the feature id for the EReference 'EKeys' reference list.
    public static readonly EREFERENCE__EKEYS: number = 23
    
    
    // EREFERENCE_FEATURE_COUNT is the number of structural features of the class EReference.
    public static readonly EREFERENCE_FEATURE_COUNT: number = 24
    
    // EREFERENCE__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly EREFERENCE__GET_EANNOTATION_ESTRING: number = 0
    // EREFERENCE__GET_CONTAINER_CLASS is the operation id for the 'getContainerClass' operation.
    public static readonly EREFERENCE__GET_CONTAINER_CLASS: number = 1
    
    // EREFERENCE_OPERATION_COUNT is the number of EREFERENCE_OPERATION_COUNT.
    public static readonly EREFERENCE_OPERATION_COUNT: number = 2
    
    // ESTRING_TO_STRING_MAP_ENTRY is the meta object id for the class EStringToStringMapEntry.
    public static readonly ESTRING_TO_STRING_MAP_ENTRY: number = 48
    
    // ESTRING_TO_STRING_MAP_ENTRY__KEY is the feature id for the EStringToStringMapEntry 'Key' attribute.
    public static readonly ESTRING_TO_STRING_MAP_ENTRY__KEY: number = 0
    
    // ESTRING_TO_STRING_MAP_ENTRY__VALUE is the feature id for the EStringToStringMapEntry 'Value' attribute.
    public static readonly ESTRING_TO_STRING_MAP_ENTRY__VALUE: number = 1
    
    
    // ESTRING_TO_STRING_MAP_ENTRY_FEATURE_COUNT is the number of structural features of the class EStringToStringMapEntry.
    public static readonly ESTRING_TO_STRING_MAP_ENTRY_FEATURE_COUNT: number = 2
    
    
    // ESTRING_TO_STRING_MAP_ENTRY_OPERATION_COUNT is the number of ESTRING_TO_STRING_MAP_ENTRY_OPERATION_COUNT.
    public static readonly ESTRING_TO_STRING_MAP_ENTRY_OPERATION_COUNT: number = 0
    
    // EGENERIC_TYPE is the meta object id for the class EGenericType.
    public static readonly EGENERIC_TYPE: number = 50
    
    // EGENERIC_TYPE__EUPPER_BOUND is the feature id for the EGenericType 'EUpperBound' containment reference.
    public static readonly EGENERIC_TYPE__EUPPER_BOUND: number = 0
    
    // EGENERIC_TYPE__ETYPE_ARGUMENTS is the feature id for the EGenericType 'ETypeArguments' containment reference list.
    public static readonly EGENERIC_TYPE__ETYPE_ARGUMENTS: number = 1
    
    // EGENERIC_TYPE__ERAW_TYPE is the feature id for the EGenericType 'ERawType' reference.
    public static readonly EGENERIC_TYPE__ERAW_TYPE: number = 2
    
    // EGENERIC_TYPE__ELOWER_BOUND is the feature id for the EGenericType 'ELowerBound' containment reference.
    public static readonly EGENERIC_TYPE__ELOWER_BOUND: number = 3
    
    // EGENERIC_TYPE__ETYPE_PARAMETER is the feature id for the EGenericType 'ETypeParameter' reference.
    public static readonly EGENERIC_TYPE__ETYPE_PARAMETER: number = 4
    
    // EGENERIC_TYPE__ECLASSIFIER is the feature id for the EGenericType 'EClassifier' reference.
    public static readonly EGENERIC_TYPE__ECLASSIFIER: number = 5
    
    
    // EGENERIC_TYPE_FEATURE_COUNT is the number of structural features of the class EGenericType.
    public static readonly EGENERIC_TYPE_FEATURE_COUNT: number = 6
    
    // EGENERIC_TYPE__IS_INSTANCE_EJAVAOBJECT is the operation id for the 'isInstance' operation.
    public static readonly EGENERIC_TYPE__IS_INSTANCE_EJAVAOBJECT: number = 0
    
    // EGENERIC_TYPE_OPERATION_COUNT is the number of EGENERIC_TYPE_OPERATION_COUNT.
    public static readonly EGENERIC_TYPE_OPERATION_COUNT: number = 1
    
    // ETYPE_PARAMETER is the meta object id for the class ETypeParameter.
    public static readonly ETYPE_PARAMETER: number = 51
    
    // ETYPE_PARAMETER__EANNOTATIONS is the feature id for the ETypeParameter 'EAnnotations' containment reference list.
    public static readonly ETYPE_PARAMETER__EANNOTATIONS: number = 0
    
    // ETYPE_PARAMETER__NAME is the feature id for the ETypeParameter 'Name' attribute.
    public static readonly ETYPE_PARAMETER__NAME: number = 1
    
    // ETYPE_PARAMETER__EBOUNDS is the feature id for the ETypeParameter 'EBounds' containment reference list.
    public static readonly ETYPE_PARAMETER__EBOUNDS: number = 2
    
    
    // ETYPE_PARAMETER_FEATURE_COUNT is the number of structural features of the class ETypeParameter.
    public static readonly ETYPE_PARAMETER_FEATURE_COUNT: number = 3
    
    // ETYPE_PARAMETER__GET_EANNOTATION_ESTRING is the operation id for the 'getEAnnotation' operation.
    public static readonly ETYPE_PARAMETER__GET_EANNOTATION_ESTRING: number = 0
    
    // ETYPE_PARAMETER_OPERATION_COUNT is the number of ETYPE_PARAMETER_OPERATION_COUNT.
    public static readonly ETYPE_PARAMETER_OPERATION_COUNT: number = 1
    
    // EBIG_DECIMAL The meta object id for the data type EBigDecimal.
    public static readonly EBIG_DECIMAL: number = 17
    // EBIG_INTEGER The meta object id for the data type EBigInteger.
    public static readonly EBIG_INTEGER: number = 18
    // EBOOLEAN The meta object id for the data type EBoolean.
    public static readonly EBOOLEAN: number = 19
    // EBOOLEAN_OBJECT The meta object id for the data type EBooleanObject.
    public static readonly EBOOLEAN_OBJECT: number = 20
    // EBYTE The meta object id for the data type EByte.
    public static readonly EBYTE: number = 21
    // EBYTE_ARRAY The meta object id for the data type EByteArray.
    public static readonly EBYTE_ARRAY: number = 22
    // EBYTE_OBJECT The meta object id for the data type EByteObject.
    public static readonly EBYTE_OBJECT: number = 23
    // ECHAR The meta object id for the data type EChar.
    public static readonly ECHAR: number = 24
    // ECHARACTER_OBJECT The meta object id for the data type ECharacterObject.
    public static readonly ECHARACTER_OBJECT: number = 25
    // EDATE The meta object id for the data type EDate.
    public static readonly EDATE: number = 26
    // EDIAGNOSTIC_CHAIN The meta object id for the data type EDiagnosticChain.
    public static readonly EDIAGNOSTIC_CHAIN: number = 27
    // EDOUBLE The meta object id for the data type EDouble.
    public static readonly EDOUBLE: number = 28
    // EDOUBLE_OBJECT The meta object id for the data type EDoubleObject.
    public static readonly EDOUBLE_OBJECT: number = 29
    // EE_LIST The meta object id for the data type EEList.
    public static readonly EE_LIST: number = 30
    // EENUMERATOR The meta object id for the data type EEnumerator.
    public static readonly EENUMERATOR: number = 31
    // EFEATURE_MAP The meta object id for the data type EFeatureMap.
    public static readonly EFEATURE_MAP: number = 32
    // EFEATURE_MAP_ENTRY The meta object id for the data type EFeatureMapEntry.
    public static readonly EFEATURE_MAP_ENTRY: number = 33
    // EFLOAT The meta object id for the data type EFloat.
    public static readonly EFLOAT: number = 34
    // EFLOAT_OBJECT The meta object id for the data type EFloatObject.
    public static readonly EFLOAT_OBJECT: number = 35
    // EINT The meta object id for the data type EInt.
    public static readonly EINT: number = 36
    // EINTEGER_OBJECT The meta object id for the data type EIntegerObject.
    public static readonly EINTEGER_OBJECT: number = 37
    // EINVOCATION_TARGET_EXCEPTION The meta object id for the data type EInvocationTargetException.
    public static readonly EINVOCATION_TARGET_EXCEPTION: number = 52
    // EJAVA_CLASS The meta object id for the data type EJavaClass.
    public static readonly EJAVA_CLASS: number = 38
    // EJAVA_OBJECT The meta object id for the data type EJavaObject.
    public static readonly EJAVA_OBJECT: number = 39
    // ELONG The meta object id for the data type ELong.
    public static readonly ELONG: number = 40
    // ELONG_OBJECT The meta object id for the data type ELongObject.
    public static readonly ELONG_OBJECT: number = 41
    // EMAP The meta object id for the data type EMap.
    public static readonly EMAP: number = 42
    // ERESOURCE The meta object id for the data type EResource.
    public static readonly ERESOURCE: number = 43
    // ERESOURCE_SET The meta object id for the data type EResourceSet.
    public static readonly ERESOURCE_SET: number = 44
    // ESHORT The meta object id for the data type EShort.
    public static readonly ESHORT: number = 45
    // ESHORT_OBJECT The meta object id for the data type EShortObject.
    public static readonly ESHORT_OBJECT: number = 46
    // ESTRING The meta object id for the data type EString.
    public static readonly ESTRING: number = 47
    // ETREE_ITERATOR The meta object id for the data type ETreeIterator.
    public static readonly ETREE_ITERATOR: number = 49
    
}

