// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group                                                 
//                                                                              
// This Source Code Form is subject to the terms of the Mozilla Public          
// License, v. 2.0. If a copy of the MPL was not distributed with this          
// file, You can obtain one at https://mozilla.org/MPL/2.0/.                    
//                                                                              
// *****************************************************************************


import {
    EAttribute,
    EClass,
    EDataType,
    EEnum,
    EOperation,
    EPackageExt,
    EReference,
    EcoreConstants,
    EcoreFactory,
    EcorePackage,
    getEcoreFactory,
} from "./internal.js"


export class EcorePackageImpl extends EPackageExt implements EcorePackage {

    private static _instance: EcorePackageImpl = null
    private _eAnnotationClass: EClass
    private _eAttributeClass: EClass
    private _eClassClass: EClass
    private _eClassifierClass: EClass
    private _eDataTypeClass: EClass
    private _eEnumClass: EClass
    private _eEnumLiteralClass: EClass
    private _eFactoryClass: EClass
    private _eGenericTypeClass: EClass
    private _eModelElementClass: EClass
    private _eNamedElementClass: EClass
    private _eObjectClass: EClass
    private _eOperationClass: EClass
    private _ePackageClass: EClass
    private _eParameterClass: EClass
    private _eReferenceClass: EClass
    private _eStringToStringMapEntryClass: EClass
    private _eStructuralFeatureClass: EClass
    private _eTypeParameterClass: EClass
    private _eTypedElementClass: EClass
    
    private _eBigDecimalType: EDataType
    private _eBigIntegerType: EDataType
    private _eBooleanType: EDataType
    private _eBooleanObjectType: EDataType
    private _eByteType: EDataType
    private _eByteArrayType: EDataType
    private _eByteObjectType: EDataType
    private _eCharType: EDataType
    private _eCharacterObjectType: EDataType
    private _eDateType: EDataType
    private _eDiagnosticChainType: EDataType
    private _eDoubleType: EDataType
    private _eDoubleObjectType: EDataType
    private _eEListType: EDataType
    private _eEnumeratorType: EDataType
    private _eFeatureMapType: EDataType
    private _eFeatureMapEntryType: EDataType
    private _eFloatType: EDataType
    private _eFloatObjectType: EDataType
    private _eIntType: EDataType
    private _eIntegerObjectType: EDataType
    private _eInvocationTargetExceptionType: EDataType
    private _eJavaClassType: EDataType
    private _eJavaObjectType: EDataType
    private _eLongType: EDataType
    private _eLongObjectType: EDataType
    private _eMapType: EDataType
    private _eResourceType: EDataType
    private _eResourceSetType: EDataType
    private _eShortType: EDataType
    private _eShortObjectType: EDataType
    private _eStringType: EDataType
    private _eTreeIteratorType: EDataType
    

    public static getInstance(): EcorePackageImpl {
        if (!this._instance) {
            this._instance = new EcorePackageImpl()
        }
        return this._instance
    }

    private constructor() {
        super()
        this.setName(EcoreConstants.eNAME)
        this.setNsPrefix(EcoreConstants.eNS_PREFIX)
        this.setNsURI(EcoreConstants.eNS_URI)
        this.setEFactoryInstance(getEcoreFactory())
        this.createPackageContents()
        this.initializePackageContents()
        this.createResource()
    }

    getEAnnotationClass(): EClass {
        return this._eAnnotationClass
    }
    
    getEAnnotation_Source(): EAttribute {
        return this._eAnnotationClass.getEStructuralFeatures().get(0) as EAttribute
    }
    
    getEAnnotation_Contents(): EReference {
        return this._eAnnotationClass.getEStructuralFeatures().get(3) as EReference
    }
    getEAnnotation_Details(): EReference {
        return this._eAnnotationClass.getEStructuralFeatures().get(1) as EReference
    }
    getEAnnotation_EModelElement(): EReference {
        return this._eAnnotationClass.getEStructuralFeatures().get(2) as EReference
    }
    getEAnnotation_References(): EReference {
        return this._eAnnotationClass.getEStructuralFeatures().get(4) as EReference
    }
    
    
    getEAttribute(): EClass {
        return this._eAttributeClass
    }
    
    getEAttribute_ID(): EAttribute {
        return this._eAttributeClass.getEStructuralFeatures().get(0) as EAttribute
    }
    
    getEAttribute_EAttributeType(): EReference {
        return this._eAttributeClass.getEStructuralFeatures().get(1) as EReference
    }
    
    
    getEClass(): EClass {
        return this._eClassClass
    }
    
    getEClass_Abstract(): EAttribute {
        return this._eClassClass.getEStructuralFeatures().get(0) as EAttribute
    }
    getEClass_Interface(): EAttribute {
        return this._eClassClass.getEStructuralFeatures().get(1) as EAttribute
    }
    
    getEClass_EAllAttributes(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(9) as EReference
    }
    getEClass_EAllContainments(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(11) as EReference
    }
    getEClass_EAllCrossReferences(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(12) as EReference
    }
    getEClass_EAllOperations(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(13) as EReference
    }
    getEClass_EAllReferences(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(10) as EReference
    }
    getEClass_EAllStructuralFeatures(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(14) as EReference
    }
    getEClass_EAllSuperTypes(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(15) as EReference
    }
    getEClass_EAttributes(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(3) as EReference
    }
    getEClass_EContainmentFeatures(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(7) as EReference
    }
    getEClass_ECrossReferenceFeatures(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(8) as EReference
    }
    getEClass_EIDAttribute(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(16) as EReference
    }
    getEClass_EOperations(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(6) as EReference
    }
    getEClass_EReferences(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(4) as EReference
    }
    getEClass_EStructuralFeatures(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(2) as EReference
    }
    getEClass_ESuperTypes(): EReference {
        return this._eClassClass.getEStructuralFeatures().get(5) as EReference
    }
    
    getEClass_GetEOperation_EInt(): EOperation {
        return this._eClassClass.getEOperations().get(6) as EOperation
    }
    getEClass_GetEStructuralFeature_EInt(): EOperation {
        return this._eClassClass.getEOperations().get(2) as EOperation
    }
    getEClass_GetEStructuralFeature_EString(): EOperation {
        return this._eClassClass.getEOperations().get(3) as EOperation
    }
    getEClass_GetFeatureCount(): EOperation {
        return this._eClassClass.getEOperations().get(1) as EOperation
    }
    getEClass_GetFeatureID_EStructuralFeature(): EOperation {
        return this._eClassClass.getEOperations().get(4) as EOperation
    }
    getEClass_GetFeatureType_EStructuralFeature(): EOperation {
        return this._eClassClass.getEOperations().get(9) as EOperation
    }
    getEClass_GetOperationCount(): EOperation {
        return this._eClassClass.getEOperations().get(5) as EOperation
    }
    getEClass_GetOperationID_EOperation(): EOperation {
        return this._eClassClass.getEOperations().get(7) as EOperation
    }
    getEClass_GetOverride_EOperation(): EOperation {
        return this._eClassClass.getEOperations().get(8) as EOperation
    }
    getEClass_IsSuperTypeOf_EClass(): EOperation {
        return this._eClassClass.getEOperations().get(0) as EOperation
    }
    
    getEClassifierClass(): EClass {
        return this._eClassifierClass
    }
    
    getEClassifier_ClassifierID(): EAttribute {
        return this._eClassifierClass.getEStructuralFeatures().get(5) as EAttribute
    }
    getEClassifier_DefaultValue(): EAttribute {
        return this._eClassifierClass.getEStructuralFeatures().get(3) as EAttribute
    }
    getEClassifier_InstanceClass(): EAttribute {
        return this._eClassifierClass.getEStructuralFeatures().get(1) as EAttribute
    }
    getEClassifier_InstanceClassName(): EAttribute {
        return this._eClassifierClass.getEStructuralFeatures().get(0) as EAttribute
    }
    getEClassifier_InstanceTypeName(): EAttribute {
        return this._eClassifierClass.getEStructuralFeatures().get(2) as EAttribute
    }
    
    getEClassifier_EPackage(): EReference {
        return this._eClassifierClass.getEStructuralFeatures().get(4) as EReference
    }
    
    getEClassifier_IsInstance_EJavaObject(): EOperation {
        return this._eClassifierClass.getEOperations().get(0) as EOperation
    }
    
    getEDataType(): EClass {
        return this._eDataTypeClass
    }
    
    getEDataType_Serializable(): EAttribute {
        return this._eDataTypeClass.getEStructuralFeatures().get(0) as EAttribute
    }
    
    
    
    getEEnum(): EClass {
        return this._eEnumClass
    }
    
    
    getEEnum_ELiterals(): EReference {
        return this._eEnumClass.getEStructuralFeatures().get(0) as EReference
    }
    
    getEEnum_GetEEnumLiteral_EString(): EOperation {
        return this._eEnumClass.getEOperations().get(0) as EOperation
    }
    getEEnum_GetEEnumLiteral_EInt(): EOperation {
        return this._eEnumClass.getEOperations().get(1) as EOperation
    }
    getEEnum_GetEEnumLiteralByLiteral_EString(): EOperation {
        return this._eEnumClass.getEOperations().get(2) as EOperation
    }
    
    getEEnumLiteral(): EClass {
        return this._eEnumLiteralClass
    }
    
    getEEnumLiteral_Instance(): EAttribute {
        return this._eEnumLiteralClass.getEStructuralFeatures().get(1) as EAttribute
    }
    getEEnumLiteral_Literal(): EAttribute {
        return this._eEnumLiteralClass.getEStructuralFeatures().get(2) as EAttribute
    }
    getEEnumLiteral_Value(): EAttribute {
        return this._eEnumLiteralClass.getEStructuralFeatures().get(0) as EAttribute
    }
    
    getEEnumLiteral_EEnum(): EReference {
        return this._eEnumLiteralClass.getEStructuralFeatures().get(3) as EReference
    }
    
    
    getEFactory(): EClass {
        return this._eFactoryClass
    }
    
    
    getEFactory_EPackage(): EReference {
        return this._eFactoryClass.getEStructuralFeatures().get(0) as EReference
    }
    
    getEFactory_ConvertToString_EDataType_EJavaObject(): EOperation {
        return this._eFactoryClass.getEOperations().get(2) as EOperation
    }
    getEFactory_Create_EClass(): EOperation {
        return this._eFactoryClass.getEOperations().get(0) as EOperation
    }
    getEFactory_CreateFromString_EDataType_EString(): EOperation {
        return this._eFactoryClass.getEOperations().get(1) as EOperation
    }
    
    getEGenericType(): EClass {
        return this._eGenericTypeClass
    }
    
    
    getEGenericType_EClassifier(): EReference {
        return this._eGenericTypeClass.getEStructuralFeatures().get(5) as EReference
    }
    getEGenericType_ELowerBound(): EReference {
        return this._eGenericTypeClass.getEStructuralFeatures().get(3) as EReference
    }
    getEGenericType_ERawType(): EReference {
        return this._eGenericTypeClass.getEStructuralFeatures().get(2) as EReference
    }
    getEGenericType_ETypeArguments(): EReference {
        return this._eGenericTypeClass.getEStructuralFeatures().get(1) as EReference
    }
    getEGenericType_ETypeParameter(): EReference {
        return this._eGenericTypeClass.getEStructuralFeatures().get(4) as EReference
    }
    getEGenericType_EUpperBound(): EReference {
        return this._eGenericTypeClass.getEStructuralFeatures().get(0) as EReference
    }
    
    getEGenericType_IsInstance_EJavaObject(): EOperation {
        return this._eGenericTypeClass.getEOperations().get(0) as EOperation
    }
    
    getEModelElement(): EClass {
        return this._eModelElementClass
    }
    
    
    getEModelElement_EAnnotations(): EReference {
        return this._eModelElementClass.getEStructuralFeatures().get(0) as EReference
    }
    
    getEModelElement_GetEAnnotation_EString(): EOperation {
        return this._eModelElementClass.getEOperations().get(0) as EOperation
    }
    
    getENamedElement(): EClass {
        return this._eNamedElementClass
    }
    
    getENamedElement_Name(): EAttribute {
        return this._eNamedElementClass.getEStructuralFeatures().get(0) as EAttribute
    }
    
    
    
    getEObject(): EClass {
        return this._eObjectClass
    }
    
    
    
    getEObject_EAllContents(): EOperation {
        return this._eObjectClass.getEOperations().get(7) as EOperation
    }
    getEObject_EClass(): EOperation {
        return this._eObjectClass.getEOperations().get(0) as EOperation
    }
    getEObject_EContainer(): EOperation {
        return this._eObjectClass.getEOperations().get(3) as EOperation
    }
    getEObject_EContainingFeature(): EOperation {
        return this._eObjectClass.getEOperations().get(4) as EOperation
    }
    getEObject_EContainmentFeature(): EOperation {
        return this._eObjectClass.getEOperations().get(5) as EOperation
    }
    getEObject_EContents(): EOperation {
        return this._eObjectClass.getEOperations().get(6) as EOperation
    }
    getEObject_ECrossReferences(): EOperation {
        return this._eObjectClass.getEOperations().get(8) as EOperation
    }
    getEObject_EGet_EStructuralFeature(): EOperation {
        return this._eObjectClass.getEOperations().get(9) as EOperation
    }
    getEObject_EGet_EStructuralFeature_EBoolean(): EOperation {
        return this._eObjectClass.getEOperations().get(10) as EOperation
    }
    getEObject_EInvoke_EOperation_EEList(): EOperation {
        return this._eObjectClass.getEOperations().get(14) as EOperation
    }
    getEObject_EIsProxy(): EOperation {
        return this._eObjectClass.getEOperations().get(1) as EOperation
    }
    getEObject_EIsSet_EStructuralFeature(): EOperation {
        return this._eObjectClass.getEOperations().get(12) as EOperation
    }
    getEObject_EResource(): EOperation {
        return this._eObjectClass.getEOperations().get(2) as EOperation
    }
    getEObject_ESet_EStructuralFeature_EJavaObject(): EOperation {
        return this._eObjectClass.getEOperations().get(11) as EOperation
    }
    getEObject_EUnset_EStructuralFeature(): EOperation {
        return this._eObjectClass.getEOperations().get(13) as EOperation
    }
    
    getEOperation(): EClass {
        return this._eOperationClass
    }
    
    getEOperation_OperationID(): EAttribute {
        return this._eOperationClass.getEStructuralFeatures().get(3) as EAttribute
    }
    
    getEOperation_EContainingClass(): EReference {
        return this._eOperationClass.getEStructuralFeatures().get(0) as EReference
    }
    getEOperation_EExceptions(): EReference {
        return this._eOperationClass.getEStructuralFeatures().get(2) as EReference
    }
    getEOperation_EParameters(): EReference {
        return this._eOperationClass.getEStructuralFeatures().get(1) as EReference
    }
    
    getEOperation_IsOverrideOf_EOperation(): EOperation {
        return this._eOperationClass.getEOperations().get(0) as EOperation
    }
    
    getEPackage(): EClass {
        return this._ePackageClass
    }
    
    getEPackage_NsPrefix(): EAttribute {
        return this._ePackageClass.getEStructuralFeatures().get(1) as EAttribute
    }
    getEPackage_NsURI(): EAttribute {
        return this._ePackageClass.getEStructuralFeatures().get(0) as EAttribute
    }
    
    getEPackage_EClassifiers(): EReference {
        return this._ePackageClass.getEStructuralFeatures().get(3) as EReference
    }
    getEPackage_EFactoryInstance(): EReference {
        return this._ePackageClass.getEStructuralFeatures().get(2) as EReference
    }
    getEPackage_ESubPackages(): EReference {
        return this._ePackageClass.getEStructuralFeatures().get(4) as EReference
    }
    getEPackage_ESuperPackage(): EReference {
        return this._ePackageClass.getEStructuralFeatures().get(5) as EReference
    }
    
    getEPackage_GetEClassifier_EString(): EOperation {
        return this._ePackageClass.getEOperations().get(0) as EOperation
    }
    
    getEParameter(): EClass {
        return this._eParameterClass
    }
    
    
    getEParameter_EOperation(): EReference {
        return this._eParameterClass.getEStructuralFeatures().get(0) as EReference
    }
    
    
    getEReference(): EClass {
        return this._eReferenceClass
    }
    
    getEReference_Container(): EAttribute {
        return this._eReferenceClass.getEStructuralFeatures().get(1) as EAttribute
    }
    getEReference_Containment(): EAttribute {
        return this._eReferenceClass.getEStructuralFeatures().get(0) as EAttribute
    }
    getEReference_ResolveProxies(): EAttribute {
        return this._eReferenceClass.getEStructuralFeatures().get(2) as EAttribute
    }
    
    getEReference_EKeys(): EReference {
        return this._eReferenceClass.getEStructuralFeatures().get(5) as EReference
    }
    getEReference_EOpposite(): EReference {
        return this._eReferenceClass.getEStructuralFeatures().get(3) as EReference
    }
    getEReference_EReferenceType(): EReference {
        return this._eReferenceClass.getEStructuralFeatures().get(4) as EReference
    }
    
    
    getEStringToStringMapEntry(): EClass {
        return this._eStringToStringMapEntryClass
    }
    
    getEStringToStringMapEntry_Key(): EAttribute {
        return this._eStringToStringMapEntryClass.getEStructuralFeatures().get(0) as EAttribute
    }
    getEStringToStringMapEntry_Value(): EAttribute {
        return this._eStringToStringMapEntryClass.getEStructuralFeatures().get(1) as EAttribute
    }
    
    
    
    getEStructuralFeature(): EClass {
        return this._eStructuralFeatureClass
    }
    
    getEStructuralFeature_Changeable(): EAttribute {
        return this._eStructuralFeatureClass.getEStructuralFeatures().get(0) as EAttribute
    }
    getEStructuralFeature_DefaultValue(): EAttribute {
        return this._eStructuralFeatureClass.getEStructuralFeatures().get(4) as EAttribute
    }
    getEStructuralFeature_DefaultValueLiteral(): EAttribute {
        return this._eStructuralFeatureClass.getEStructuralFeatures().get(3) as EAttribute
    }
    getEStructuralFeature_Derived(): EAttribute {
        return this._eStructuralFeatureClass.getEStructuralFeatures().get(6) as EAttribute
    }
    getEStructuralFeature_FeatureID(): EAttribute {
        return this._eStructuralFeatureClass.getEStructuralFeatures().get(8) as EAttribute
    }
    getEStructuralFeature_Transient(): EAttribute {
        return this._eStructuralFeatureClass.getEStructuralFeatures().get(2) as EAttribute
    }
    getEStructuralFeature_Unsettable(): EAttribute {
        return this._eStructuralFeatureClass.getEStructuralFeatures().get(5) as EAttribute
    }
    getEStructuralFeature_Volatile(): EAttribute {
        return this._eStructuralFeatureClass.getEStructuralFeatures().get(1) as EAttribute
    }
    
    getEStructuralFeature_EContainingClass(): EReference {
        return this._eStructuralFeatureClass.getEStructuralFeatures().get(7) as EReference
    }
    
    getEStructuralFeature_GetContainerClass(): EOperation {
        return this._eStructuralFeatureClass.getEOperations().get(0) as EOperation
    }
    
    getETypeParameter(): EClass {
        return this._eTypeParameterClass
    }
    
    
    getETypeParameter_EBounds(): EReference {
        return this._eTypeParameterClass.getEStructuralFeatures().get(0) as EReference
    }
    
    
    getETypedElement(): EClass {
        return this._eTypedElementClass
    }
    
    getETypedElement_LowerBound(): EAttribute {
        return this._eTypedElementClass.getEStructuralFeatures().get(2) as EAttribute
    }
    getETypedElement_Many(): EAttribute {
        return this._eTypedElementClass.getEStructuralFeatures().get(4) as EAttribute
    }
    getETypedElement_Ordered(): EAttribute {
        return this._eTypedElementClass.getEStructuralFeatures().get(0) as EAttribute
    }
    getETypedElement_Required(): EAttribute {
        return this._eTypedElementClass.getEStructuralFeatures().get(5) as EAttribute
    }
    getETypedElement_Unique(): EAttribute {
        return this._eTypedElementClass.getEStructuralFeatures().get(1) as EAttribute
    }
    getETypedElement_UpperBound(): EAttribute {
        return this._eTypedElementClass.getEStructuralFeatures().get(3) as EAttribute
    }
    
    getETypedElement_EType(): EReference {
        return this._eTypedElementClass.getEStructuralFeatures().get(6) as EReference
    }
    
    
    getEBigDecimal(): EDataType {
        return this._eBigDecimalType
    }
    getEBigInteger(): EDataType {
        return this._eBigIntegerType
    }
    getEBoolean(): EDataType {
        return this._eBooleanType
    }
    getEBooleanObject(): EDataType {
        return this._eBooleanObjectType
    }
    getEByte(): EDataType {
        return this._eByteType
    }
    getEByteArray(): EDataType {
        return this._eByteArrayType
    }
    getEByteObject(): EDataType {
        return this._eByteObjectType
    }
    getEChar(): EDataType {
        return this._eCharType
    }
    getECharacterObject(): EDataType {
        return this._eCharacterObjectType
    }
    getEDate(): EDataType {
        return this._eDateType
    }
    getEDiagnosticChain(): EDataType {
        return this._eDiagnosticChainType
    }
    getEDouble(): EDataType {
        return this._eDoubleType
    }
    getEDoubleObject(): EDataType {
        return this._eDoubleObjectType
    }
    getEEList(): EDataType {
        return this._eEListType
    }
    getEEnumerator(): EDataType {
        return this._eEnumeratorType
    }
    getEFeatureMap(): EDataType {
        return this._eFeatureMapType
    }
    getEFeatureMapEntry(): EDataType {
        return this._eFeatureMapEntryType
    }
    getEFloat(): EDataType {
        return this._eFloatType
    }
    getEFloatObject(): EDataType {
        return this._eFloatObjectType
    }
    getEInt(): EDataType {
        return this._eIntType
    }
    getEIntegerObject(): EDataType {
        return this._eIntegerObjectType
    }
    getEInvocationTargetException(): EDataType {
        return this._eInvocationTargetExceptionType
    }
    getEJavaClass(): EDataType {
        return this._eJavaClassType
    }
    getEJavaObject(): EDataType {
        return this._eJavaObjectType
    }
    getELong(): EDataType {
        return this._eLongType
    }
    getELongObject(): EDataType {
        return this._eLongObjectType
    }
    getEMap(): EDataType {
        return this._eMapType
    }
    getEResource(): EDataType {
        return this._eResourceType
    }
    getEResourceSet(): EDataType {
        return this._eResourceSetType
    }
    getEShort(): EDataType {
        return this._eShortType
    }
    getEShortObject(): EDataType {
        return this._eShortObjectType
    }
    getEString(): EDataType {
        return this._eStringType
    }
    getETreeIterator(): EDataType {
        return this._eTreeIteratorType
    }
    


    private createPackageContents(): void {
        let factory = getEcoreFactory();
    
        this._eAnnotationClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EANNOTATION)
        factory.createEAttributeFromContainerAndClassID(this._eAnnotationClass, EcoreConstants.EANNOTATION__SOURCE)
        factory.createEReferenceFromContainerAndClassID(this._eAnnotationClass, EcoreConstants.EANNOTATION__DETAILS)
        factory.createEReferenceFromContainerAndClassID(this._eAnnotationClass, EcoreConstants.EANNOTATION__EMODEL_ELEMENT)
        factory.createEReferenceFromContainerAndClassID(this._eAnnotationClass, EcoreConstants.EANNOTATION__CONTENTS)
        factory.createEReferenceFromContainerAndClassID(this._eAnnotationClass, EcoreConstants.EANNOTATION__REFERENCES)
        
    
        this._eAttributeClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EATTRIBUTE)
        factory.createEAttributeFromContainerAndClassID(this._eAttributeClass, EcoreConstants.EATTRIBUTE__ID)
        factory.createEReferenceFromContainerAndClassID(this._eAttributeClass, EcoreConstants.EATTRIBUTE__EATTRIBUTE_TYPE)
        
    
        this._eClassClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.ECLASS)
        factory.createEAttributeFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__ABSTRACT)
        factory.createEAttributeFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__INTERFACE)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__ESTRUCTURAL_FEATURES)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__EATTRIBUTES)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__EREFERENCES)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__ESUPER_TYPES)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__EOPERATIONS)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__ECONTAINMENT_FEATURES)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__ECROSS_REFERENCE_FEATURES)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__EALL_ATTRIBUTES)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__EALL_REFERENCES)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__EALL_CONTAINMENTS)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__EALL_CROSS_REFERENCES)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__EALL_OPERATIONS)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__EALL_STRUCTURAL_FEATURES)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__EALL_SUPER_TYPES)
        factory.createEReferenceFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__EID_ATTRIBUTE)
        factory.createEOperationFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__IS_SUPER_TYPE_OF_ECLASS)
        factory.createEOperationFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__GET_FEATURE_COUNT)
        factory.createEOperationFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__GET_ESTRUCTURAL_FEATURE_EINT)
        factory.createEOperationFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__GET_ESTRUCTURAL_FEATURE_ESTRING)
        factory.createEOperationFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__GET_FEATURE_ID_ESTRUCTURALFEATURE)
        factory.createEOperationFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__GET_OPERATION_COUNT)
        factory.createEOperationFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__GET_EOPERATION_EINT)
        factory.createEOperationFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__GET_OPERATION_ID_EOPERATION)
        factory.createEOperationFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__GET_OVERRIDE_EOPERATION)
        factory.createEOperationFromContainerAndClassID(this._eClassClass, EcoreConstants.ECLASS__GET_FEATURE_TYPE_ESTRUCTURALFEATURE)
        
    
        this._eClassifierClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.ECLASSIFIER)
        factory.createEAttributeFromContainerAndClassID(this._eClassifierClass, EcoreConstants.ECLASSIFIER__INSTANCE_CLASS_NAME)
        factory.createEAttributeFromContainerAndClassID(this._eClassifierClass, EcoreConstants.ECLASSIFIER__INSTANCE_CLASS)
        factory.createEAttributeFromContainerAndClassID(this._eClassifierClass, EcoreConstants.ECLASSIFIER__INSTANCE_TYPE_NAME)
        factory.createEAttributeFromContainerAndClassID(this._eClassifierClass, EcoreConstants.ECLASSIFIER__DEFAULT_VALUE)
        factory.createEReferenceFromContainerAndClassID(this._eClassifierClass, EcoreConstants.ECLASSIFIER__EPACKAGE)
        factory.createEAttributeFromContainerAndClassID(this._eClassifierClass, EcoreConstants.ECLASSIFIER__CLASSIFIER_ID)
        factory.createEOperationFromContainerAndClassID(this._eClassifierClass, EcoreConstants.ECLASSIFIER__IS_INSTANCE_EJAVAOBJECT)
        
    
        this._eDataTypeClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EDATA_TYPE)
        factory.createEAttributeFromContainerAndClassID(this._eDataTypeClass, EcoreConstants.EDATA_TYPE__SERIALIZABLE)
        
    
        this._eEnumClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EENUM)
        factory.createEReferenceFromContainerAndClassID(this._eEnumClass, EcoreConstants.EENUM__ELITERALS)
        factory.createEOperationFromContainerAndClassID(this._eEnumClass, EcoreConstants.EENUM__GET_EENUM_LITERAL_ESTRING)
        factory.createEOperationFromContainerAndClassID(this._eEnumClass, EcoreConstants.EENUM__GET_EENUM_LITERAL_EINT)
        factory.createEOperationFromContainerAndClassID(this._eEnumClass, EcoreConstants.EENUM__GET_EENUM_LITERAL_BY_LITERAL_ESTRING)
        
    
        this._eEnumLiteralClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EENUM_LITERAL)
        factory.createEAttributeFromContainerAndClassID(this._eEnumLiteralClass, EcoreConstants.EENUM_LITERAL__VALUE)
        factory.createEAttributeFromContainerAndClassID(this._eEnumLiteralClass, EcoreConstants.EENUM_LITERAL__INSTANCE)
        factory.createEAttributeFromContainerAndClassID(this._eEnumLiteralClass, EcoreConstants.EENUM_LITERAL__LITERAL)
        factory.createEReferenceFromContainerAndClassID(this._eEnumLiteralClass, EcoreConstants.EENUM_LITERAL__EENUM)
        
    
        this._eFactoryClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EFACTORY)
        factory.createEReferenceFromContainerAndClassID(this._eFactoryClass, EcoreConstants.EFACTORY__EPACKAGE)
        factory.createEOperationFromContainerAndClassID(this._eFactoryClass, EcoreConstants.EFACTORY__CREATE_ECLASS)
        factory.createEOperationFromContainerAndClassID(this._eFactoryClass, EcoreConstants.EFACTORY__CREATE_FROM_STRING_EDATATYPE_ESTRING)
        factory.createEOperationFromContainerAndClassID(this._eFactoryClass, EcoreConstants.EFACTORY__CONVERT_TO_STRING_EDATATYPE_EJAVAOBJECT)
        
    
        this._eGenericTypeClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EGENERIC_TYPE)
        factory.createEReferenceFromContainerAndClassID(this._eGenericTypeClass, EcoreConstants.EGENERIC_TYPE__EUPPER_BOUND)
        factory.createEReferenceFromContainerAndClassID(this._eGenericTypeClass, EcoreConstants.EGENERIC_TYPE__ETYPE_ARGUMENTS)
        factory.createEReferenceFromContainerAndClassID(this._eGenericTypeClass, EcoreConstants.EGENERIC_TYPE__ERAW_TYPE)
        factory.createEReferenceFromContainerAndClassID(this._eGenericTypeClass, EcoreConstants.EGENERIC_TYPE__ELOWER_BOUND)
        factory.createEReferenceFromContainerAndClassID(this._eGenericTypeClass, EcoreConstants.EGENERIC_TYPE__ETYPE_PARAMETER)
        factory.createEReferenceFromContainerAndClassID(this._eGenericTypeClass, EcoreConstants.EGENERIC_TYPE__ECLASSIFIER)
        factory.createEOperationFromContainerAndClassID(this._eGenericTypeClass, EcoreConstants.EGENERIC_TYPE__IS_INSTANCE_EJAVAOBJECT)
        
    
        this._eModelElementClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EMODEL_ELEMENT)
        factory.createEReferenceFromContainerAndClassID(this._eModelElementClass, EcoreConstants.EMODEL_ELEMENT__EANNOTATIONS)
        factory.createEOperationFromContainerAndClassID(this._eModelElementClass, EcoreConstants.EMODEL_ELEMENT__GET_EANNOTATION_ESTRING)
        
    
        this._eNamedElementClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.ENAMED_ELEMENT)
        factory.createEAttributeFromContainerAndClassID(this._eNamedElementClass, EcoreConstants.ENAMED_ELEMENT__NAME)
        
    
        this._eObjectClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EOBJECT)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__ECLASS)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__EIS_PROXY)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__ERESOURCE)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__ECONTAINER)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__ECONTAINING_FEATURE)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__ECONTAINMENT_FEATURE)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__ECONTENTS)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__EALL_CONTENTS)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__ECROSS_REFERENCES)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__EGET_ESTRUCTURALFEATURE)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__EGET_ESTRUCTURALFEATURE_EBOOLEAN)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__ESET_ESTRUCTURALFEATURE_EJAVAOBJECT)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__EIS_SET_ESTRUCTURALFEATURE)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__EUNSET_ESTRUCTURALFEATURE)
        factory.createEOperationFromContainerAndClassID(this._eObjectClass, EcoreConstants.EOBJECT__EINVOKE_EOPERATION_EELIST)
        
    
        this._eOperationClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EOPERATION)
        factory.createEReferenceFromContainerAndClassID(this._eOperationClass, EcoreConstants.EOPERATION__ECONTAINING_CLASS)
        factory.createEReferenceFromContainerAndClassID(this._eOperationClass, EcoreConstants.EOPERATION__EPARAMETERS)
        factory.createEReferenceFromContainerAndClassID(this._eOperationClass, EcoreConstants.EOPERATION__EEXCEPTIONS)
        factory.createEAttributeFromContainerAndClassID(this._eOperationClass, EcoreConstants.EOPERATION__OPERATION_ID)
        factory.createEOperationFromContainerAndClassID(this._eOperationClass, EcoreConstants.EOPERATION__IS_OVERRIDE_OF_EOPERATION)
        
    
        this._ePackageClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EPACKAGE)
        factory.createEAttributeFromContainerAndClassID(this._ePackageClass, EcoreConstants.EPACKAGE__NS_URI)
        factory.createEAttributeFromContainerAndClassID(this._ePackageClass, EcoreConstants.EPACKAGE__NS_PREFIX)
        factory.createEReferenceFromContainerAndClassID(this._ePackageClass, EcoreConstants.EPACKAGE__EFACTORY_INSTANCE)
        factory.createEReferenceFromContainerAndClassID(this._ePackageClass, EcoreConstants.EPACKAGE__ECLASSIFIERS)
        factory.createEReferenceFromContainerAndClassID(this._ePackageClass, EcoreConstants.EPACKAGE__ESUB_PACKAGES)
        factory.createEReferenceFromContainerAndClassID(this._ePackageClass, EcoreConstants.EPACKAGE__ESUPER_PACKAGE)
        factory.createEOperationFromContainerAndClassID(this._ePackageClass, EcoreConstants.EPACKAGE__GET_ECLASSIFIER_ESTRING)
        
    
        this._eParameterClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EPARAMETER)
        factory.createEReferenceFromContainerAndClassID(this._eParameterClass, EcoreConstants.EPARAMETER__EOPERATION)
        
    
        this._eReferenceClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.EREFERENCE)
        factory.createEAttributeFromContainerAndClassID(this._eReferenceClass, EcoreConstants.EREFERENCE__CONTAINMENT)
        factory.createEAttributeFromContainerAndClassID(this._eReferenceClass, EcoreConstants.EREFERENCE__CONTAINER)
        factory.createEAttributeFromContainerAndClassID(this._eReferenceClass, EcoreConstants.EREFERENCE__RESOLVE_PROXIES)
        factory.createEReferenceFromContainerAndClassID(this._eReferenceClass, EcoreConstants.EREFERENCE__EOPPOSITE)
        factory.createEReferenceFromContainerAndClassID(this._eReferenceClass, EcoreConstants.EREFERENCE__EREFERENCE_TYPE)
        factory.createEReferenceFromContainerAndClassID(this._eReferenceClass, EcoreConstants.EREFERENCE__EKEYS)
        
    
        this._eStringToStringMapEntryClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.ESTRING_TO_STRING_MAP_ENTRY)
        factory.createEAttributeFromContainerAndClassID(this._eStringToStringMapEntryClass, EcoreConstants.ESTRING_TO_STRING_MAP_ENTRY__KEY)
        factory.createEAttributeFromContainerAndClassID(this._eStringToStringMapEntryClass, EcoreConstants.ESTRING_TO_STRING_MAP_ENTRY__VALUE)
        
    
        this._eStructuralFeatureClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.ESTRUCTURAL_FEATURE)
        factory.createEAttributeFromContainerAndClassID(this._eStructuralFeatureClass, EcoreConstants.ESTRUCTURAL_FEATURE__CHANGEABLE)
        factory.createEAttributeFromContainerAndClassID(this._eStructuralFeatureClass, EcoreConstants.ESTRUCTURAL_FEATURE__VOLATILE)
        factory.createEAttributeFromContainerAndClassID(this._eStructuralFeatureClass, EcoreConstants.ESTRUCTURAL_FEATURE__TRANSIENT)
        factory.createEAttributeFromContainerAndClassID(this._eStructuralFeatureClass, EcoreConstants.ESTRUCTURAL_FEATURE__DEFAULT_VALUE_LITERAL)
        factory.createEAttributeFromContainerAndClassID(this._eStructuralFeatureClass, EcoreConstants.ESTRUCTURAL_FEATURE__DEFAULT_VALUE)
        factory.createEAttributeFromContainerAndClassID(this._eStructuralFeatureClass, EcoreConstants.ESTRUCTURAL_FEATURE__UNSETTABLE)
        factory.createEAttributeFromContainerAndClassID(this._eStructuralFeatureClass, EcoreConstants.ESTRUCTURAL_FEATURE__DERIVED)
        factory.createEReferenceFromContainerAndClassID(this._eStructuralFeatureClass, EcoreConstants.ESTRUCTURAL_FEATURE__ECONTAINING_CLASS)
        factory.createEAttributeFromContainerAndClassID(this._eStructuralFeatureClass, EcoreConstants.ESTRUCTURAL_FEATURE__FEATURE_ID)
        factory.createEOperationFromContainerAndClassID(this._eStructuralFeatureClass, EcoreConstants.ESTRUCTURAL_FEATURE__GET_CONTAINER_CLASS)
        
    
        this._eTypeParameterClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.ETYPE_PARAMETER)
        factory.createEReferenceFromContainerAndClassID(this._eTypeParameterClass, EcoreConstants.ETYPE_PARAMETER__EBOUNDS)
        
    
        this._eTypedElementClass = factory.createEClassFromContainerAndClassID(this, EcoreConstants.ETYPED_ELEMENT)
        factory.createEAttributeFromContainerAndClassID(this._eTypedElementClass, EcoreConstants.ETYPED_ELEMENT__ORDERED)
        factory.createEAttributeFromContainerAndClassID(this._eTypedElementClass, EcoreConstants.ETYPED_ELEMENT__UNIQUE)
        factory.createEAttributeFromContainerAndClassID(this._eTypedElementClass, EcoreConstants.ETYPED_ELEMENT__LOWER_BOUND)
        factory.createEAttributeFromContainerAndClassID(this._eTypedElementClass, EcoreConstants.ETYPED_ELEMENT__UPPER_BOUND)
        factory.createEAttributeFromContainerAndClassID(this._eTypedElementClass, EcoreConstants.ETYPED_ELEMENT__MANY)
        factory.createEAttributeFromContainerAndClassID(this._eTypedElementClass, EcoreConstants.ETYPED_ELEMENT__REQUIRED)
        factory.createEReferenceFromContainerAndClassID(this._eTypedElementClass, EcoreConstants.ETYPED_ELEMENT__ETYPE)
        

        this._eBigDecimalType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EBIG_DECIMAL)
        this._eBigIntegerType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EBIG_INTEGER)
        this._eBooleanType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EBOOLEAN)
        this._eBooleanObjectType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EBOOLEAN_OBJECT)
        this._eByteType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EBYTE)
        this._eByteArrayType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EBYTE_ARRAY)
        this._eByteObjectType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EBYTE_OBJECT)
        this._eCharType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.ECHAR)
        this._eCharacterObjectType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.ECHARACTER_OBJECT)
        this._eDateType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EDATE)
        this._eDiagnosticChainType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EDIAGNOSTIC_CHAIN)
        this._eDoubleType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EDOUBLE)
        this._eDoubleObjectType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EDOUBLE_OBJECT)
        this._eEListType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EE_LIST)
        this._eEnumeratorType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EENUMERATOR)
        this._eFeatureMapType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EFEATURE_MAP)
        this._eFeatureMapEntryType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EFEATURE_MAP_ENTRY)
        this._eFloatType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EFLOAT)
        this._eFloatObjectType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EFLOAT_OBJECT)
        this._eIntType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EINT)
        this._eIntegerObjectType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EINTEGER_OBJECT)
        this._eInvocationTargetExceptionType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EINVOCATION_TARGET_EXCEPTION)
        this._eJavaClassType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EJAVA_CLASS)
        this._eJavaObjectType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EJAVA_OBJECT)
        this._eLongType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.ELONG)
        this._eLongObjectType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.ELONG_OBJECT)
        this._eMapType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.EMAP)
        this._eResourceType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.ERESOURCE)
        this._eResourceSetType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.ERESOURCE_SET)
        this._eShortType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.ESHORT)
        this._eShortObjectType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.ESHORT_OBJECT)
        this._eStringType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.ESTRING)
        this._eTreeIteratorType = factory.createEDataTypeFromContainerAndClassID(this, EcoreConstants.ETREE_ITERATOR)
        
    }

    private initializePackageContents(): void {

        this._eAnnotationClass.getESuperTypes().add(this._eModelElementClass)
        this._eAttributeClass.getESuperTypes().add(this._eStructuralFeatureClass)
        this._eClassClass.getESuperTypes().add(this._eClassifierClass)
        this._eClassifierClass.getESuperTypes().add(this._eNamedElementClass)
        this._eDataTypeClass.getESuperTypes().add(this._eClassifierClass)
        this._eEnumClass.getESuperTypes().add(this._eDataTypeClass)
        this._eEnumLiteralClass.getESuperTypes().add(this._eNamedElementClass)
        this._eFactoryClass.getESuperTypes().add(this._eModelElementClass)
        this._eNamedElementClass.getESuperTypes().add(this._eModelElementClass)
        this._eOperationClass.getESuperTypes().add(this._eTypedElementClass)
        this._ePackageClass.getESuperTypes().add(this._eNamedElementClass)
        this._eParameterClass.getESuperTypes().add(this._eTypedElementClass)
        this._eReferenceClass.getESuperTypes().add(this._eStructuralFeatureClass)
        this._eStructuralFeatureClass.getESuperTypes().add(this._eTypedElementClass)
        this._eTypeParameterClass.getESuperTypes().add(this._eNamedElementClass)
        this._eTypedElementClass.getESuperTypes().add(this._eNamedElementClass)
        

        this.initEClass(this._eAnnotationClass, "EAnnotation", "@masagroup/ecore/EAnnotation", false, false)
        this.initEAttribute(this.getEAnnotation_Source(), this.getEString(), "source", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEReference(this.getEAnnotation_Details(), this.getEStringToStringMapEntry(), null, "details", "", 0, -1, false, false, true, true, false, false, true, false, true)
        this.initEReference(this.getEAnnotation_EModelElement(), this.getEModelElement(), this.getEModelElement_EAnnotations(), "eModelElement", "", 0, 1, true, false, true, false, false, false, true, false, true)
        this.initEReference(this.getEAnnotation_Contents(), this.getEObject(), null, "contents", "", 0, -1, false, false, true, true, false, false, true, false, true)
        this.initEReference(this.getEAnnotation_References(), this.getEObject(), null, "references", "", 0, -1, false, false, true, false, true, false, true, false, true)
        
        this.initEClass(this._eAttributeClass, "EAttribute", "@masagroup/ecore/EAttribute", false, false)
        this.initEAttribute(this.getEAttribute_ID(), this.getEBoolean(), "iD", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEReference(this.getEAttribute_EAttributeType(), this.getEDataType(), null, "eAttributeType", "", 1, 1, true, true, false, false, true, false, true, true, true)
        
        this.initEClass(this._eClassClass, "EClass", "@masagroup/ecore/EClass", false, false)
        this.initEAttribute(this.getEClass_Abstract(), this.getEBoolean(), "abstract", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEClass_Interface(), this.getEBoolean(), "interface", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEReference(this.getEClass_EStructuralFeatures(), this.getEStructuralFeature(), this.getEStructuralFeature_EContainingClass(), "eStructuralFeatures", "", 0, -1, false, false, true, true, false, false, true, false, true)
        this.initEReference(this.getEClass_EAttributes(), this.getEAttribute(), null, "eAttributes", "", 0, -1, true, false, false, false, true, false, true, true, true)
        this.initEReference(this.getEClass_EReferences(), this.getEReference(), null, "eReferences", "", 0, -1, true, false, false, false, true, false, true, true, true)
        this.initEReference(this.getEClass_ESuperTypes(), this.getEClass(), null, "eSuperTypes", "", 0, -1, false, false, true, false, true, false, true, false, true)
        this.initEReference(this.getEClass_EOperations(), this.getEOperation(), this.getEOperation_EContainingClass(), "eOperations", "", 0, -1, false, false, true, true, false, false, true, false, true)
        this.initEReference(this.getEClass_EContainmentFeatures(), this.getEStructuralFeature(), null, "eContainmentFeatures", "", 0, -1, true, false, false, false, true, false, true, true, true)
        this.initEReference(this.getEClass_ECrossReferenceFeatures(), this.getEStructuralFeature(), null, "eCrossReferenceFeatures", "", 0, -1, true, false, false, false, true, false, true, true, true)
        this.initEReference(this.getEClass_EAllAttributes(), this.getEAttribute(), null, "eAllAttributes", "", 0, -1, true, false, false, false, true, false, true, true, true)
        this.initEReference(this.getEClass_EAllReferences(), this.getEReference(), null, "eAllReferences", "", 0, -1, true, false, false, false, true, false, true, true, true)
        this.initEReference(this.getEClass_EAllContainments(), this.getEReference(), null, "eAllContainments", "", 0, -1, true, false, false, false, true, false, true, true, true)
        this.initEReference(this.getEClass_EAllCrossReferences(), this.getEReference(), null, "eAllCrossReferences", "", 0, -1, true, false, false, false, true, false, true, true, true)
        this.initEReference(this.getEClass_EAllOperations(), this.getEOperation(), null, "eAllOperations", "", 0, -1, true, false, false, false, true, false, true, true, true)
        this.initEReference(this.getEClass_EAllStructuralFeatures(), this.getEStructuralFeature(), null, "eAllStructuralFeatures", "", 0, -1, true, false, false, false, true, false, true, true, true)
        this.initEReference(this.getEClass_EAllSuperTypes(), this.getEClass(), null, "eAllSuperTypes", "", 0, -1, true, false, false, false, true, false, true, true, true)
        this.initEReference(this.getEClass_EIDAttribute(), this.getEAttribute(), null, "eIDAttribute", "", 0, 1, true, false, false, false, false, false, true, true, true)
        {
            let operation = this.getEClass_IsSuperTypeOf_EClass()
            this.initEOperation(operation, this.getEBoolean(), "isSuperTypeOf", 0, 1, true, true)
            this.addEParameter(operation, this.getEClass(), "someClass", 0, 1, true, true)
        }
        this.initEOperation(this.getEClass_GetFeatureCount(), this.getEInt(), "getFeatureCount", 0, 1, true, true)
        {
            let operation = this.getEClass_GetEStructuralFeature_EInt()
            this.initEOperation(operation, this.getEStructuralFeature(), "getEStructuralFeature", 0, 1, true, true)
            this.addEParameter(operation, this.getEInt(), "featureID", 0, 1, true, true)
        }
        {
            let operation = this.getEClass_GetEStructuralFeature_EString()
            this.initEOperation(operation, this.getEStructuralFeature(), "getEStructuralFeature", 0, 1, true, true)
            this.addEParameter(operation, this.getEString(), "featureName", 0, 1, true, true)
        }
        {
            let operation = this.getEClass_GetFeatureID_EStructuralFeature()
            this.initEOperation(operation, this.getEInt(), "getFeatureID", 0, 1, true, true)
            this.addEParameter(operation, this.getEStructuralFeature(), "feature", 0, 1, true, true)
        }
        this.initEOperation(this.getEClass_GetOperationCount(), this.getEInt(), "getOperationCount", 0, 1, true, true)
        {
            let operation = this.getEClass_GetEOperation_EInt()
            this.initEOperation(operation, this.getEOperation(), "getEOperation", 0, 1, true, true)
            this.addEParameter(operation, this.getEInt(), "operationID", 0, 1, true, true)
        }
        {
            let operation = this.getEClass_GetOperationID_EOperation()
            this.initEOperation(operation, this.getEInt(), "getOperationID", 0, 1, true, true)
            this.addEParameter(operation, this.getEOperation(), "operation", 0, 1, true, true)
        }
        {
            let operation = this.getEClass_GetOverride_EOperation()
            this.initEOperation(operation, this.getEOperation(), "getOverride", 0, 1, true, true)
            this.addEParameter(operation, this.getEOperation(), "operation", 0, 1, true, true)
        }
        {
            let operation = this.getEClass_GetFeatureType_EStructuralFeature()
            this.initEOperation(operation, this.getEClassifierClass(), "getFeatureType", 0, 1, true, true)
            this.addEParameter(operation, this.getEStructuralFeature(), "feature", 0, 1, true, true)
        }
        
        this.initEClass(this._eClassifierClass, "EClassifier", "@masagroup/ecore/EClassifier", true, false)
        this.initEAttribute(this.getEClassifier_InstanceClassName(), this.getEString(), "instanceClassName", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEClassifier_InstanceClass(), this.getEJavaClass(), "instanceClass", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEClassifier_InstanceTypeName(), this.getEString(), "instanceTypeName", "", 0, 1, false, true, true, false, true, false, true, false)
        this.initEAttribute(this.getEClassifier_DefaultValue(), this.getEJavaObject(), "defaultValue", "", 0, 1, true, true, false, false, true, true, true, false)
        this.initEAttribute(this.getEClassifier_ClassifierID(), this.getEInt(), "classifierID", "-1", 0, 1, true, false, true, false, true, false, true, false)
        this.initEReference(this.getEClassifier_EPackage(), this.getEPackage(), this.getEPackage_EClassifiers(), "ePackage", "", 0, 1, true, false, false, false, true, false, true, false, true)
        {
            let operation = this.getEClassifier_IsInstance_EJavaObject()
            this.initEOperation(operation, this.getEBoolean(), "isInstance", 0, 1, true, true)
            this.addEParameter(operation, this.getEJavaObject(), "object", 0, 1, true, true)
        }
        
        this.initEClass(this._eDataTypeClass, "EDataType", "@masagroup/ecore/EDataType", false, false)
        this.initEAttribute(this.getEDataType_Serializable(), this.getEBoolean(), "serializable", "true", 0, 1, false, false, true, false, true, false, true, false)
        
        this.initEClass(this._eEnumClass, "EEnum", "@masagroup/ecore/EEnum", false, false)
        this.initEReference(this.getEEnum_ELiterals(), this.getEEnumLiteral(), this.getEEnumLiteral_EEnum(), "eLiterals", "", 0, -1, false, false, true, true, false, false, true, false, true)
        {
            let operation = this.getEEnum_GetEEnumLiteral_EString()
            this.initEOperation(operation, this.getEEnumLiteral(), "getEEnumLiteral", 0, 1, true, true)
            this.addEParameter(operation, this.getEString(), "name", 0, 1, true, true)
        }
        {
            let operation = this.getEEnum_GetEEnumLiteral_EInt()
            this.initEOperation(operation, this.getEEnumLiteral(), "getEEnumLiteral", 0, 1, true, true)
            this.addEParameter(operation, this.getEInt(), "value", 0, 1, true, true)
        }
        {
            let operation = this.getEEnum_GetEEnumLiteralByLiteral_EString()
            this.initEOperation(operation, this.getEEnumLiteral(), "getEEnumLiteralByLiteral", 0, 1, true, true)
            this.addEParameter(operation, this.getEString(), "literal", 0, 1, true, true)
        }
        
        this.initEClass(this._eEnumLiteralClass, "EEnumLiteral", "@masagroup/ecore/EEnumLiteral", false, false)
        this.initEAttribute(this.getEEnumLiteral_Value(), this.getEInt(), "value", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEEnumLiteral_Instance(), this.getEEnumerator(), "instance", "", 0, 1, true, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEEnumLiteral_Literal(), this.getEString(), "literal", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEReference(this.getEEnumLiteral_EEnum(), this.getEEnum(), this.getEEnum_ELiterals(), "eEnum", "", 0, 1, true, false, false, false, false, false, true, false, true)
        
        this.initEClass(this._eFactoryClass, "EFactory", "@masagroup/ecore/EFactory", false, false)
        this.initEReference(this.getEFactory_EPackage(), this.getEPackage(), this.getEPackage_EFactoryInstance(), "ePackage", "", 1, 1, true, false, true, false, false, false, true, false, true)
        {
            let operation = this.getEFactory_Create_EClass()
            this.initEOperation(operation, this.getEObject(), "create", 0, 1, true, true)
            this.addEParameter(operation, this.getEClass(), "eClass", 0, 1, true, true)
        }
        {
            let operation = this.getEFactory_CreateFromString_EDataType_EString()
            this.initEOperation(operation, this.getEJavaObject(), "createFromString", 0, 1, true, true)
            this.addEParameter(operation, this.getEDataType(), "eDataType", 0, 1, true, true)
            this.addEParameter(operation, this.getEString(), "literalValue", 0, 1, true, true)
        }
        {
            let operation = this.getEFactory_ConvertToString_EDataType_EJavaObject()
            this.initEOperation(operation, this.getEString(), "convertToString", 0, 1, true, true)
            this.addEParameter(operation, this.getEDataType(), "eDataType", 0, 1, true, true)
            this.addEParameter(operation, this.getEJavaObject(), "instanceValue", 0, 1, true, true)
        }
        
        this.initEClass(this._eGenericTypeClass, "EGenericType", "@masagroup/ecore/EGenericType", false, false)
        this.initEReference(this.getEGenericType_EUpperBound(), this.getEGenericType(), null, "eUpperBound", "", 0, 1, false, false, true, true, false, false, true, false, true)
        this.initEReference(this.getEGenericType_ETypeArguments(), this.getEGenericType(), null, "eTypeArguments", "", 0, -1, false, false, true, true, false, false, true, false, true)
        this.initEReference(this.getEGenericType_ERawType(), this.getEClassifierClass(), null, "eRawType", "", 1, 1, true, false, false, false, true, false, true, true, true)
        this.initEReference(this.getEGenericType_ELowerBound(), this.getEGenericType(), null, "eLowerBound", "", 0, 1, false, false, true, true, false, false, true, false, true)
        this.initEReference(this.getEGenericType_ETypeParameter(), this.getETypeParameter(), null, "eTypeParameter", "", 0, 1, false, false, true, false, false, false, true, false, true)
        this.initEReference(this.getEGenericType_EClassifier(), this.getEClassifierClass(), null, "eClassifier", "", 0, 1, false, false, true, false, true, false, true, false, true)
        {
            let operation = this.getEGenericType_IsInstance_EJavaObject()
            this.initEOperation(operation, this.getEBoolean(), "isInstance", 0, 1, true, true)
            this.addEParameter(operation, this.getEJavaObject(), "object", 0, 1, true, true)
        }
        
        this.initEClass(this._eModelElementClass, "EModelElement", "@masagroup/ecore/EModelElement", true, false)
        this.initEReference(this.getEModelElement_EAnnotations(), this.getEAnnotationClass(), this.getEAnnotation_EModelElement(), "eAnnotations", "", 0, -1, false, false, true, true, false, false, true, false, true)
        {
            let operation = this.getEModelElement_GetEAnnotation_EString()
            this.initEOperation(operation, this.getEAnnotationClass(), "getEAnnotation", 0, 1, true, true)
            this.addEParameter(operation, this.getEString(), "source", 0, 1, true, true)
        }
        
        this.initEClass(this._eNamedElementClass, "ENamedElement", "@masagroup/ecore/ENamedElement", true, false)
        this.initEAttribute(this.getENamedElement_Name(), this.getEString(), "name", "", 0, 1, false, false, true, false, true, false, true, false)
        
        this.initEClass(this._eObjectClass, "EObject", "@masagroup/ecore/EObject", false, false)
        this.initEOperation(this.getEObject_EClass(), this.getEClass(), "eClass", 0, 1, true, true)
        this.initEOperation(this.getEObject_EIsProxy(), this.getEBoolean(), "eIsProxy", 0, 1, true, true)
        this.initEOperation(this.getEObject_EResource(), this.getEResource(), "eResource", 0, 1, true, true)
        this.initEOperation(this.getEObject_EContainer(), this.getEObject(), "eContainer", 0, 1, true, true)
        this.initEOperation(this.getEObject_EContainingFeature(), this.getEStructuralFeature(), "eContainingFeature", 0, 1, true, true)
        this.initEOperation(this.getEObject_EContainmentFeature(), this.getEReference(), "eContainmentFeature", 0, 1, true, true)
        this.initEOperation(this.getEObject_EContents(), this.getEEList(), "eContents", 0, 1, true, true)
        this.initEOperation(this.getEObject_EAllContents(), this.getETreeIterator(), "eAllContents", 0, 1, true, true)
        this.initEOperation(this.getEObject_ECrossReferences(), this.getEEList(), "eCrossReferences", 0, 1, true, true)
        {
            let operation = this.getEObject_EGet_EStructuralFeature()
            this.initEOperation(operation, this.getEJavaObject(), "eGet", 0, 1, true, true)
            this.addEParameter(operation, this.getEStructuralFeature(), "feature", 0, 1, true, true)
        }
        {
            let operation = this.getEObject_EGet_EStructuralFeature_EBoolean()
            this.initEOperation(operation, this.getEJavaObject(), "eGet", 0, 1, true, true)
            this.addEParameter(operation, this.getEStructuralFeature(), "feature", 0, 1, true, true)
            this.addEParameter(operation, this.getEBoolean(), "resolve", 0, 1, true, true)
        }
        {
            let operation = this.getEObject_ESet_EStructuralFeature_EJavaObject()
            this.initEOperation(operation, null, "eSet", 0, 1, true, true)
            this.addEParameter(operation, null, "feature", 0, 1, true, true)
            this.addEParameter(operation, null, "newValue", 0, 1, true, true)
        }
        {
            let operation = this.getEObject_EIsSet_EStructuralFeature()
            this.initEOperation(operation, this.getEBoolean(), "eIsSet", 0, 1, true, true)
            this.addEParameter(operation, this.getEStructuralFeature(), "feature", 0, 1, true, true)
        }
        {
            let operation = this.getEObject_EUnset_EStructuralFeature()
            this.initEOperation(operation, null, "eUnset", 0, 1, true, true)
            this.addEParameter(operation, null, "feature", 0, 1, true, true)
        }
        {
            let operation = this.getEObject_EInvoke_EOperation_EEList()
            this.initEOperation(operation, this.getEJavaObject(), "eInvoke", 0, 1, true, true)
            this.addEParameter(operation, this.getEOperation(), "operation", 0, 1, true, true)
            this.addEParameter(operation, this.getEEList(), "arguments", 0, 1, true, true)
        }
        
        this.initEClass(this._eOperationClass, "EOperation", "@masagroup/ecore/EOperation", false, false)
        this.initEAttribute(this.getEOperation_OperationID(), this.getEInt(), "operationID", "-1", 0, 1, false, false, true, false, true, false, true, false)
        this.initEReference(this.getEOperation_EContainingClass(), this.getEClass(), this.getEClass_EOperations(), "eContainingClass", "", 0, 1, true, false, false, false, false, false, true, false, true)
        this.initEReference(this.getEOperation_EParameters(), this.getEParameter(), this.getEParameter_EOperation(), "eParameters", "", 0, -1, false, false, true, true, false, false, true, false, true)
        this.initEReference(this.getEOperation_EExceptions(), this.getEClassifierClass(), null, "eExceptions", "", 0, -1, false, false, true, false, true, true, true, false, true)
        {
            let operation = this.getEOperation_IsOverrideOf_EOperation()
            this.initEOperation(operation, this.getEBoolean(), "isOverrideOf", 0, 1, true, true)
            this.addEParameter(operation, this.getEOperation(), "someOperation", 0, 1, true, true)
        }
        
        this.initEClass(this._ePackageClass, "EPackage", "@masagroup/ecore/EPackage", false, false)
        this.initEAttribute(this.getEPackage_NsURI(), this.getEString(), "nsURI", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEPackage_NsPrefix(), this.getEString(), "nsPrefix", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEReference(this.getEPackage_EFactoryInstance(), this.getEFactory(), this.getEFactory_EPackage(), "eFactoryInstance", "", 1, 1, true, false, true, true, false, false, true, false, true)
        this.initEReference(this.getEPackage_EClassifiers(), this.getEClassifierClass(), this.getEClassifier_EPackage(), "eClassifiers", "", 0, -1, false, false, true, true, true, false, true, false, true)
        this.initEReference(this.getEPackage_ESubPackages(), this.getEPackage(), this.getEPackage_ESuperPackage(), "eSubPackages", "", 0, -1, false, false, true, true, true, false, true, false, true)
        this.initEReference(this.getEPackage_ESuperPackage(), this.getEPackage(), this.getEPackage_ESubPackages(), "eSuperPackage", "", 0, 1, true, false, false, false, true, false, true, false, true)
        {
            let operation = this.getEPackage_GetEClassifier_EString()
            this.initEOperation(operation, this.getEClassifierClass(), "getEClassifier", 0, 1, true, true)
            this.addEParameter(operation, this.getEString(), "name", 0, 1, true, true)
        }
        
        this.initEClass(this._eParameterClass, "EParameter", "@masagroup/ecore/EParameter", false, false)
        this.initEReference(this.getEParameter_EOperation(), this.getEOperation(), this.getEOperation_EParameters(), "eOperation", "", 0, 1, true, false, false, false, false, false, true, false, true)
        
        this.initEClass(this._eReferenceClass, "EReference", "@masagroup/ecore/EReference", false, false)
        this.initEAttribute(this.getEReference_Containment(), this.getEBoolean(), "containment", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEReference_Container(), this.getEBoolean(), "container", "", 0, 1, true, true, false, false, true, true, true, false)
        this.initEAttribute(this.getEReference_ResolveProxies(), this.getEBoolean(), "resolveProxies", "true", 0, 1, false, false, true, false, true, false, true, false)
        this.initEReference(this.getEReference_EOpposite(), this.getEReference(), null, "eOpposite", "", 0, 1, false, false, true, false, true, false, true, false, true)
        this.initEReference(this.getEReference_EReferenceType(), this.getEClass(), null, "eReferenceType", "", 1, 1, true, true, false, false, true, false, true, true, true)
        this.initEReference(this.getEReference_EKeys(), this.getEAttribute(), null, "eKeys", "", 0, -1, false, false, true, false, true, false, true, false, true)
        
        this.initEClass(this._eStringToStringMapEntryClass, "EStringToStringMapEntry", "@masagroup/ecore/EMapEntry", false, false)
        this.initEAttribute(this.getEStringToStringMapEntry_Key(), this.getEString(), "key", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEStringToStringMapEntry_Value(), this.getEString(), "value", "", 0, 1, false, false, true, false, true, false, true, false)
        
        this.initEClass(this._eStructuralFeatureClass, "EStructuralFeature", "@masagroup/ecore/EStructuralFeature", true, false)
        this.initEAttribute(this.getEStructuralFeature_Changeable(), this.getEBoolean(), "changeable", "true", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEStructuralFeature_Volatile(), this.getEBoolean(), "volatile", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEStructuralFeature_Transient(), this.getEBoolean(), "transient", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEStructuralFeature_DefaultValueLiteral(), this.getEString(), "defaultValueLiteral", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEStructuralFeature_DefaultValue(), this.getEJavaObject(), "defaultValue", "", 0, 1, true, true, true, false, true, true, true, false)
        this.initEAttribute(this.getEStructuralFeature_Unsettable(), this.getEBoolean(), "unsettable", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEStructuralFeature_Derived(), this.getEBoolean(), "derived", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getEStructuralFeature_FeatureID(), this.getEInt(), "featureID", "-1", 0, 1, true, false, true, false, true, false, true, false)
        this.initEReference(this.getEStructuralFeature_EContainingClass(), this.getEClass(), this.getEClass_EStructuralFeatures(), "eContainingClass", "", 0, 1, true, false, false, false, false, false, true, false, true)
        this.initEOperation(this.getEStructuralFeature_GetContainerClass(), this.getEJavaClass(), "getContainerClass", 0, 1, true, true)
        
        this.initEClass(this._eTypeParameterClass, "ETypeParameter", "@masagroup/ecore/ETypeParameter", false, false)
        this.initEReference(this.getETypeParameter_EBounds(), this.getEGenericType(), null, "eBounds", "", 0, -1, false, false, true, true, false, false, true, false, true)
        
        this.initEClass(this._eTypedElementClass, "ETypedElement", "@masagroup/ecore/ETypedElement", true, false)
        this.initEAttribute(this.getETypedElement_Ordered(), this.getEBoolean(), "ordered", "true", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getETypedElement_Unique(), this.getEBoolean(), "unique", "true", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getETypedElement_LowerBound(), this.getEInt(), "lowerBound", "", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getETypedElement_UpperBound(), this.getEInt(), "upperBound", "1", 0, 1, false, false, true, false, true, false, true, false)
        this.initEAttribute(this.getETypedElement_Many(), this.getEBoolean(), "many", "", 0, 1, true, true, false, false, true, true, true, false)
        this.initEAttribute(this.getETypedElement_Required(), this.getEBoolean(), "required", "", 0, 1, true, true, false, false, true, true, true, false)
        this.initEReference(this.getETypedElement_EType(), this.getEClassifierClass(), null, "eType", "", 0, 1, false, false, true, false, true, true, true, false, true)
        
        this.initEDataType(this.getEBigDecimal(), "EBigDecimal", "number","0",true)
        this.initEDataType(this.getEBigInteger(), "EBigInteger", "number","0",true)
        this.initEDataType(this.getEBoolean(), "EBoolean", "boolean","false",true)
        this.initEDataType(this.getEBooleanObject(), "EBooleanObject", "boolean","false",true)
        this.initEDataType(this.getEByte(), "EByte", "byte","0",true)
        this.initEDataType(this.getEByteArray(), "EByteArray", "Uint8Array","",true)
        this.initEDataType(this.getEByteObject(), "EByteObject", "number","0",true)
        this.initEDataType(this.getEChar(), "EChar", "number","0",true)
        this.initEDataType(this.getECharacterObject(), "ECharacterObject", "number","0",true)
        this.initEDataType(this.getEDate(), "EDate", "Date","",true)
        this.initEDataType(this.getEDiagnosticChain(), "EDiagnosticChain", "@masagroup/ecore/EDiagnosticChain","",false)
        this.initEDataType(this.getEDouble(), "EDouble", "number","0.0",true)
        this.initEDataType(this.getEDoubleObject(), "EDoubleObject", "number","0",true)
        this.initEDataType(this.getEEList(), "EEList", "@masagroup/ecore/EList","",false)
        this.initEDataType(this.getEEnumerator(), "EEnumerator", "any","",false)
        this.initEDataType(this.getEFeatureMap(), "EFeatureMap", "any","",false)
        this.initEDataType(this.getEFeatureMapEntry(), "EFeatureMapEntry", "any","",false)
        this.initEDataType(this.getEFloat(), "EFloat", "number","0.0",true)
        this.initEDataType(this.getEFloatObject(), "EFloatObject", "number","0",true)
        this.initEDataType(this.getEInt(), "EInt", "number","0",true)
        this.initEDataType(this.getEIntegerObject(), "EIntegerObject", "number","0",true)
        this.initEDataType(this.getEInvocationTargetException(), "EInvocationTargetException", "java.lang.reflect.InvocationTargetException","",false)
        this.initEDataType(this.getEJavaClass(), "EJavaClass", "any","",true)
        this.initEDataType(this.getEJavaObject(), "EJavaObject", "any","",true)
        this.initEDataType(this.getELong(), "ELong", "number","0",true)
        this.initEDataType(this.getELongObject(), "ELongObject", "number","0",true)
        this.initEDataType(this.getEMap(), "EMap", "@masagroup/ecore/EMap","",false)
        this.initEDataType(this.getEResource(), "EResource", "@masagroup/ecore/EResource","",false)
        this.initEDataType(this.getEResourceSet(), "EResourceSet", "@masagroup/ecore/EResourceSet","",false)
        this.initEDataType(this.getEShort(), "EShort", "number","0",true)
        this.initEDataType(this.getEShortObject(), "EShortObject", "number","0",true)
        this.initEDataType(this.getEString(), "EString", "string","",true)
        this.initEDataType(this.getETreeIterator(), "ETreeIterator", "IterableIterator","",false)
        
    }

}

