// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

import { anything, capture, instance, mock, verify } from "ts-mockito"
import { describe, expect, test } from "vitest"
import { EAdapter, ENamedElementImpl, EcoreConstants, getEcorePackage } from "./internal.js"

describe("ENamedElementImpl", () => {
    test("eStaticClass", () => {
        const o = new ENamedElementImpl()
        expect(o.eStaticClass()).toBe(getEcorePackage().getENamedElement())
    })

    test("getName", () => {
        const o = new ENamedElementImpl()
        // get default value
        expect(o.getName()).toBe("")
    })

    test("setName", () => {
        const o = new ENamedElementImpl()
        const value = "Test String"

        // add listener
        const mockAdapter = mock<EAdapter>()
        const adapter = instance(mockAdapter)
        o.eAdapters().add(adapter)

        // set value
        o.setName(value)

        // checks
        verify(mockAdapter.notifyChanged(anything())).once()
        const [notification] = capture(mockAdapter.notifyChanged).last()
        expect(notification.getNotifier()).toBe(o)
        expect(notification.getOldValue()).toBe("")
        expect(notification.getNewValue()).toBe(value)
        expect(notification.getPosition()).toBe(-1)
    })

    test("eGetFromID", () => {
        const o = new ENamedElementImpl()
        expect(() => o.eGetFromID(-1, true)).toThrow(Error)
        expect(o.eGetFromID(EcoreConstants.ENAMED_ELEMENT__NAME, true)).toStrictEqual(o.getName())
    })

    test("eSetFromID", () => {
        const o = new ENamedElementImpl()
        expect(() => o.eSetFromID(-1, null)).toThrow(Error)
        {
            const value = "Test String"
            o.eSetFromID(EcoreConstants.ENAMED_ELEMENT__NAME, value)
            expect(o.eGetFromID(EcoreConstants.ENAMED_ELEMENT__NAME, false)).toBe(value)
        }
    })

    test("eIsSetFromID", () => {
        const o = new ENamedElementImpl()
        expect(() => o.eIsSetFromID(-1)).toThrow(Error)
        expect(o.eIsSetFromID(EcoreConstants.ENAMED_ELEMENT__NAME)).toBeFalsy()
    })

    test("eUnsetFromID", () => {
        const o = new ENamedElementImpl()
        expect(() => o.eUnsetFromID(-1)).toThrow(Error)
        {
            o.eUnsetFromID(EcoreConstants.ENAMED_ELEMENT__NAME)
            const v = o.eGetFromID(EcoreConstants.ENAMED_ELEMENT__NAME, false)
            expect(v).toBe("")
        }
    })
})
