// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

import deepEqual from "deep-equal"
import { anything, capture, instance, mock, reset, verify, when } from "ts-mockito"
import {
    EAdapter,
    EClass,
    EList,
    ENotificationChain,
    ENotifyingList,
    EOPPOSITE_FEATURE_BASE,
    EObject,
    EObjectImpl,
    EObjectInternal,
    EObjectList,
    EOperation,
    EReference,
    EResource,
    EResourceSet,
    EStructuralFeature,
    EcoreConstants,
    ImmutableEList,
    URI,
    getEcorePackage,
    isEObjectList,
} from "./internal"

describe("EObjectImpl", () => {
    test("eStaticClass", () => {
        let o = new EObjectImpl()
        expect(o.eStaticClass()).toBe(getEcorePackage().getEObject())
    })
})
