// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group                                                 
//                                                                              
// This Source Code Form is subject to the terms of the Mozilla Public          
// License, v. 2.0. If a copy of the MPL was not distributed with this          
// file, You can obtain one at https://mozilla.org/MPL/2.0/.                    
//                                                                              
// *****************************************************************************



import {
    EClass,
    EClassifier,
    EList,
    EParameter,
    ETypedElement,
} from "./internal.js"


export interface EOperation extends ETypedElement {
    // Attributes
    getOperationID(): number
    setOperationID( newOperationID : number ): void
    
    
    // References
    getEContainingClass(): EClass
    
    getEParameters(): EList<EParameter>
    
    getEExceptions(): EList<EClassifier>
    unSetEExceptions(): void
    
    
    // Operations
    isOverrideOf(someOperation: EOperation): boolean
    
}

