// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

import { EClass, EClassifier, EList, EParameter, ETypedElement } from "./internal";

export interface EOperation extends ETypedElement {
    // Attributes
    operationID: number;

    // References
    readonly eContainingClass: EClass;
    readonly eParameters: EList<EParameter>;
    readonly eExceptions: EList<EClassifier>;
    unSetEExceptions(): void;

    // Operations
    isOverrideOf(someOperation: EOperation): boolean;
}
