// Code generated by soft.generator.ts. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2024 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

import { EClassifier, EFactory, EList, ENamedElement } from "./internal.js"

export interface EPackage extends ENamedElement {
    // nsURI
    getNsURI(): string
    setNsURI(newNsURI: string): void

    // nsPrefix
    getNsPrefix(): string
    setNsPrefix(newNsPrefix: string): void

    // eFactoryInstance
    getEFactoryInstance(): EFactory
    setEFactoryInstance(newEFactoryInstance: EFactory): void

    // eClassifiers
    getEClassifiers(): EList<EClassifier>

    // eSubPackages
    getESubPackages(): EList<EPackage>

    // eSuperPackage
    getESuperPackage(): EPackage

    // operations
    getEClassifier(name: string): EClassifier
}
