// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2020 MASA Group
//
// *****************************************************************************

export * from "./Buffer.js"
export * from "./Collection.js"
export * from "./Constants.js"
export * from "./EAdapter.js"
export * from "./EDiagnostic.js"
export * from "./EFeatureMapEntry.js"
export * from "./EList.js"
export * from "./EMap.js"
export * from "./EMapEntry.js"
export * from "./ENotification.js"
export * from "./ENotificationChain.js"
export * from "./ENotifier.js"
export * from "./ENotifyingList.js"
export * from "./ENotifyingList.js"
export * from "./EObjectInternal.js"
export * from "./EObjectList.js"
export * from "./EObjectIDManager.js"
export * from "./EPackageRegistry.js"
export * from "./EResource.js"
export * from "./EResourceListener.js"
export * from "./EResourceInternal.js"
export * from "./EResourceSet.js"
export * from "./ETreeIterator.js"
export * from "./EURIConverter.js"
export * from "./EURIHandler.js"

export * from "./EModelElement.js"
export * from "./ENamedElement.js"
export * from "./ETypedElement.js"
export * from "./EStructuralFeature.js"
export * from "./EAttribute.js"
export * from "./EAnnotation.js"
export * from "./EClassifier.js"
export * from "./EClass.js"
export * from "./EDataType.js"
export * from "./EEnum.js"
export * from "./EEnumLiteral.js"
export * from "./EFactory.js"
export * from "./EObject.js"
export * from "./EOperation.js"
export * from "./EPackage.js"
export * from "./EParameter.js"
export * from "./EReference.js"
export * from "./EStringToStringMapEntry.js"
export * from "./EGenericType.js"
export * from "./ETypeParameter.js"
export * from "./EcoreConstants.js"
export * from "./EcorePackage.js"
export * from "./EcoreFactory.js"

export * from "./AbstractEList.js"
export * from "./BasicEList.js"
export * from "./BasicEMap.js"
export * from "./AbstractEAdapter.js"
export * from "./AbstractNotification.js"
export * from "./AbstractENotifier.js"
export * from "./AbstractEObject.js"
export * from "./Notification.js"
export * from "./NotificationChain.js"
export * from "./ImmutableEList.js"
export * from "./AbstractNotifyingList.js"
export * from "./BasicEDataTypeList.js"
export * from "./BasicEObject.js"
export * from "./BasicEObjectList.js"
export * from "./BasicEObjectMap.js"
export * from "./ENotifierImpl.js"
export * from "./EObjectImpl.js"
export * from "./EContentAdapter.js"
export * from "./DynamicEObjectImpl.js"

export * from "./EModelElementImpl.js"
export * from "./EModelElementExt.js"
export * from "./ENamedElementImpl.js"
export * from "./ETypedElementImpl.js"
export * from "./ETypedElementExt.js"
export * from "./EStructuralFeatureImpl.js"
export * from "./EStructuralFeatureExt.js"
export * from "./EAttributeImpl.js"
export * from "./EAttributeExt.js"
export * from "./EAnnotationImpl.js"
export * from "./EClassifierImpl.js"
export * from "./EClassifierExt.js"
export * from "./EClassImpl.js"
export * from "./EClassExt.js"
export * from "./EDataTypeImpl.js"
export * from "./EDataTypeExt.js"
export * from "./EEnumImpl.js"
export * from "./EEnumExt.js"
export * from "./EEnumLiteralImpl.js"
export * from "./EEnumLiteralExt.js"
export * from "./EFactoryImpl.js"
export * from "./EFactoryExt.js"
export * from "./EOperationImpl.js"
export * from "./EOperationExt.js"
export * from "./EPackageImpl.js"
export * from "./EPackageExt.js"
export * from "./EParameterImpl.js"
export * from "./EReferenceImpl.js"
export * from "./EReferenceExt.js"
export * from "./EStringToStringMapEntryImpl.js"
export * from "./EGenericTypeImpl.js"
export * from "./ETypeParameterImpl.js"
export * from "./EcorePackageImpl.js"
export * from "./EcoreFactoryImpl.js"
export * from "./EcoreFactoryExt.js"

export * from "./ExtendedMetaData.js"
export * from "./FileURIHandler.js"
export * from "./EDiagnosticImpl.js"
export * from "./EURIConverterImpl.js"
export * from "./EResourceImpl.js"
export * from "./EResourceSetImpl.js"
export * from "./UniqueIDManager.js"

export * from "./ECodec.js"
export * from "./EEncoder.js"
export * from "./EDecoder.js"
export * from "./ECodecRegistry.js"
export * from "./ECodecRegistryImpl.js"
export * from "./XMLCodec.js"
export * from "./XMLEncoder.js"
export * from "./XMLDecoder.js"
export * from "./XMLNamespaces.js"
export * from "./XMICodec.js"
export * from "./NoCodec.js"
export * from "./BinaryCodec.js"
export * from "./BinaryEncoder.js"
export * from "./BinaryDecoder.js"

export * from "./XMLProcessor.js"
export * from "./XMIProcessor.js"

export * from "./EPackageRegistryImpl.js"

export * from "./DeepCopy.js"
export * from "./DeepEqual.js"
export * from "./EcoreUtils.js"
export * from "./URI.js"
